### ISSUE TITLE
[BUG] Low contrast for menu

### ISSUE THREAD

**Issue by m-terlinde** [dfir-iris/iris-web#102]
**Describe the bug**
The contrast for the menu on the left side differs from section to section. `Investigatoin` and child items are better visible than `Manage` and `Dashboard`. See screenshot.

**To Reproduce**
1. Go to any case
4. See colours

**Expected behavior**
Make everything clearly visible, even for people with bad eyes :D.
Maybe even a high contrast mode would be good in adition?

**Screenshots**
![image](https://user-images.githubusercontent.com/10097313/165122165-afca3181-6978-4c03-8cfe-e56938f87432.png)

**Desktop:**
 - OS: Win 11
 - Browser FF
 - Version 99.0.1

**Comment by whikernel** [comment]
Thanks for the report ! There's indeed still quite a lot of UI issues, we're trying to fix them along the way :)  
Well fix this one in the next patch 👍  For the high contrast mode, we take the idea ! The roadmap is already pretty loaded so it might take time to implement though.  

Cheers 
_-- Side note; if you have bad eyes, please never use our dark theme, ever --_
