### ISSUE TITLE
[BUG] Event Category search field broken

### ISSUE THREAD

**Issue by m-terlinde** [dfir-iris/iris-web#103]
**Describe the bug**
On the timeline page, the search for the `Event Category` does not work

**To Reproduce**
1. Go to `Timeline`
2. Click on `Add Event`
3. Click on `Unspecified` under `Event Category`
4. Try to type `Per` to search for the `Persistance`
5. Nothing happens

**Expected behavior**
Filter for the rigth category.

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Firefox
 - Version 99.0.1

**Comment by whikernel** [comment]
Hi @m-terlinde 

We'll update the documentation, but the search field works by keyword `keyword: searched_value`.  
At the moment, the following keywords are available : 

- asset
- tag
- description
- category
- raw
- startDate
- endDate
-  title
-  source

If you input a search without keyword, it is ignored.   
Are you using the keywords ? If not could you please check with it and it's working as expected ? 

Cheers

**Comment by m-terlinde** [comment]
Hey, @whikernel,

I'm quite not sure, if we are talking about the same thing.

I was confuesd by the search field in that pop-up:
![image](https://user-images.githubusercontent.com/10097313/165492919-16a0394e-9e1a-4414-afe6-416e6696e059.png)

Trying to use keywords there doesn't feel helpful there.

Cheers,
Matthias

**Comment by whikernel** [comment]
Oh my bad, I thought you were talking about the filtering bar in timeline. 
Yes you're right, the filter is broken there - we'll fix that 👍

**Comment by whikernel** [comment]
**Note** : this is actually already patched by @sebastiandemmer in the PR #101. It will be fixed when merged 👍

**Comment by whikernel** [comment]
Closed with #108
