### ISSUE TITLE
[BUG] Event Category search field stays open

### ISSUE THREAD

**Issue by m-terlinde** [dfir-iris/iris-web#104]
**Describe the bug**
The Event Category search field stays open, if you close the `add Event` pop-up

**To Reproduce**
1. Go to `Timeline`
2. Click on `Add event`
3. Click on `Unspecified` at `Event category`
4. Hit `Esc` key
5. See error

**Expected behavior**
Close the dropdown, when `Esc` is pressed

**Screenshots**
![image](https://user-images.githubusercontent.com/10097313/165492358-1bd4a67c-e1d6-4659-86b9-6a32073803ed.png)

**Desktop:**
 - OS: Win11
 - Browser FF
 - Version 99.0.1

**Comment by whikernel** [comment]
This is patched by @sebastiandemmer in the PR https://github.com/dfir-iris/iris-web/pull/101. It will be fixed when merged.

**Comment by whikernel** [comment]
Closed with #108
