### ISSUE TITLE
[BUG] Setup fails due to an authentication failure

### ISSUE THREAD

**Issue by vortex1409** [dfir-iris/iris-web#114]
**Describe the bug**
Containers initialize however an authentication failure occurs for user "raptor" as indicated on container: iris-web_db_1. 

```
2022-05-23 07:31:46.798 UTC [28] FATAL:  password authentication failed for user "raptor"
2022-05-23 07:31:46.798 UTC [28] DETAIL:  Password does not match for user "raptor".
```

In addition container iris-web_app_1 shows the following error.
`psycopg2.OperationalError: FATAL:  password authentication failed for user "raptor"`

**To Reproduce**
1. Follow quick start setup
2. Change DB passwords in .env file (Note the only change to the .env file made is the passwords changed to a more secure value.)
3. Run docker-compose

**Expected behavior**
Instances launch and application is available

**Comment by Ektoplasma** [comment]
Hello @vortex1409,

I think you kept the same docker volume from previous instance. If that's the case, then it's the expected behavior. If it's really a new setup, then I suggest you modify the passwords in .env before you execute `docker-compose up`
