### ISSUE TITLE
[BUG] First launch - app creates tables before the db service is connected

### ISSUE THREAD

**Issue by Ektoplasma** [dfir-iris/iris-web#133]
**Describe the bug**
For some setups, the app tries to create tables before the db could start the postgresql service properly. Therefore, the app crashes (Connection refused). We should modify https://github.com/dfir-iris/iris-web/blob/master/source/app/post_init.py#L72 and test the availability of the database before any table creation.

**To Reproduce**
1. docker compose build
2. docker compose up
3. The app crashes because it cannot connect to the database

Again, the bug is triggered on some setups. 

**Server:**
 - Hypervisor KVM, VM Debian

**Comment by AnotherShen** [comment]
Replicated in Ubuntu Server 18.04 and 22.04 (VMWare Workstation 16).

**Comment by whikernel** [comment]
@AnotherShen thanks for the feedback. That's interesting - we'll need to do more testing on that.

**Comment by weslambert** [comment]
I've run into this issue many times when starting the containers from scratch. I think there should be some improved retry logic here so that the app can try to re-connect for a longer duration. Otherwise, a restart of the web app container seems to fix the issue.

**Comment by Ektoplasma** [comment]
Has been fixed a long time ago :) thx @weslambert
