### ISSUE TITLE
[FR] Allow API key override for initial user (or specify per user during scripted creation)

### ISSUE THREAD

**Issue by weslambert** [dfir-iris/iris-web#134]
**Is your feature request related to a problem? Please describe.**
There is currently no way to obtain an API key for the initial user, unless logged in via the web interface.

**Describe the solution you'd like**
I would like to be able to specify my own API key or override the default API key generation (similar to how this is done with the `administrator` account and it's password) so that the API key can be obtained and used for interacting with the API and bootstrapping the environment before users log into the web interface.

**Describe alternatives you've considered**
I've considered querying the local Postgres database, although this is messy and not a great practice, in general.

**Comment by legoguy1000** [comment]
So we're doing the same type of automation visa Ansible and deploying on kubernetes. My solution was doing exactly what I said, querying postgres and setting an API key directly to the DB.
