### ISSUE TITLE
[FR] Publish iris-webapp Docker image

### ISSUE THREAD

**Issue by jnimmo** [dfir-iris/iris-web#145]
*Please ensure your feature request is not already on the roadmap or associated with an issue. This can be checked [here](https://github.com/orgs/dfir-iris/projects/1/views/4).*

**Is your feature request related to a problem? Please describe.**
The Docker image is difficult to build in some environments (such as behind a web proxy) due to the number of dependencies. Providing a Docker image will make it significantly easier for people to test out Iris. 

**Describe the solution you'd like**
Configure Github Actions to build and publish Docker images for iriswebapp_app to Docker hub or GHCR.
The steps required to configure this are:
- Create a Docker Hub account for DFIR Iris
- Configure the secrets in this repository (https://docs.docker.com/ci-cd/github-actions/) 
- PR from https://github.com/dfir-iris/iris-web/compare/master...jnimmo:iris-web:master to add the Github action

**Describe alternatives you've considered**
Setting up a pipeline to publish the image to Docker Hub myself, however this doesn't seem like a sensible option.

**Additional context**
Ideally would add an additional action to lint the code or run some tests over before building the image. Happy to assist with configuring this if required.

**Comment by jnimmo** [comment]
I've published an example build of 1.4.5 to jnimmo/iris-webapp:1.4.5
(https://hub.docker.com/repository/docker/jnimmo/iris-webapp)

**Comment by whikernel** [comment]
Hi @jnimmo, 

Thanks for the issue! We were indeed thinking of pushing IRIS to Docker Hub. The main _issue_ was to push all the dockers, but you actually have a fair point - we only need to have iris-web there.  
We'll  add this, eiher for the 1.4.5 or the upcoming 1.5.0 👍 

For the tests, it's big subject that we need to work on and we'd definitely be glad to have some help on that matter. 

Cheers

**Comment by jnimmo** [comment]
Any progress on pre-building the Docker images? :)

**Comment by Johnwulp** [comment]
We would also need a pre-build image since we have already a reverse proxy and reserved ports :-)

**Comment by whikernel** [comment]
This is now fixed starting from v2.4.9
