### ISSUE TITLE
[BUG] Hardcoded RabbitMQ address

### ISSUE THREAD

**Issue by legoguy1000** [dfir-iris/iris-web#148]
**Describe the bug**
Currently the Rabbit MQ url is hardcoded base on the below.  We're deploying DFIR on Kubernetes which doesn't have the networking as Docker.  If i deploy RabbitMQ in the same pod as DFIR, its actually `localhost` to connect to it or if 2 separate pods whatever the service name is.
```
broker_url = "amqp://localhost" if not os.getenv('DOCKERIZED') else "amqp://rabbitmq"
```

**To Reproduce**
1. Create a K8S deployment yaml that contains DFIR, Worker, RabbitMQ, Postres, Nginx
2. Add all applicable ENV vars and set `DOCKERIZED=1`

**Expected behavior**
I expect to be able to specific the url to RabbitMQ instead of it being hardcoded. Add ENV/Config options to set the RabbitMQ url just like the database.

**Screenshots**

**Additional context**
I was able to overcome this issue by overriding the hosts file in my DFIR and worker containers to point rabbitmq to 127.0.0.1, see https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/.

**Comment by whikernel** [comment]
Hi @legoguy1000! 

I think this is fixed in this PR : https://github.com/dfir-iris/iris-web/pull/131. 
It is in the code of the develop branch and will be publish - hopefully - soon 👍 

Cheers

**Comment by legoguy1000** [comment]
sweet!!
