### ISSUE TITLE
[FR] Enable Module config via API

### ISSUE THREAD

**Issue by legoguy1000** [dfir-iris/iris-web#149]
*Please ensure your feature request is not already on the roadmap or associated with an issue. This can be checked [here](https://github.com/orgs/dfir-iris/projects/1/views/4).*

**Is your feature request related to a problem? Please describe.**
Currently we are deploying DFIR into a a K8S cluster using Ansible to automate the deployment and configuration of everything.  This includes the module configurations like MISP.  Currently this requires a session cookie and CSRF token to make those API calls as opposed to just having an API token.

**Describe the solution you'd like**
Allow for Authentication for module config using just API token.

**Describe alternatives you've considered**
To get around this, i'm currently using ansible to get a session token and regex to find the csrf token to then add both of those to a follow on API call to configure the module.  While this is doable, it was a big pain to figure out and would just be som uch easier for the future to not have to and just use an API token.

**Additional context**

**Comment by whikernel** [comment]
Hi @legoguy1000! 

There is actually an endpoint which allows to upload a configuration with the API. It appears we missed it in the API reference - we'll update it. 
You can push a module configuration with the following : 

```bash
curl '<iris_server>/manage/modules/import-config/<module_id>?cid=1' -X POST   \
        --header 'Authorization: Bearer <API_key>' \
        --header 'Content-Type: application/json' \
        --data-raw $'{"module_configuration":"<your_escaped_config>"}'
```

- **your_escaped_config**: shall have the exact same structure of the one when you're doing a `Export config` from the UI. The JSON needs to be just a string and thus escaped.  
- **module_id**: is the ID of the module you want to update the config of 

Let us know if it helps. 
Cheers

**Comment by legoguy1000** [comment]
Tracking. I also was not fully clear.bthats great for the whole config which I may end up using anyways but currently Im trying to change individual config parameters. That's where I'm running into the csrf token stuff.

**Comment by legoguy1000** [comment]
OK nevermind.  I was able to get everything working the way I wanted too.  It was my testing in postman that screwed everything up.  When I would call the API using jus the API token, the API returns a `Set-Cookie` header with a session cookie even though we're using the API token. Postman auto adds that cookie to follow on requests which then requires a CSRF token.  If u clear all the cookies, everything works as expected and no my ansible is able to use just the API token.  

The only valid thing that came out of this is that the Manage Module endpoints need to be added to the docs.

**Comment by whikernel** [comment]
Indeed we're using the session cookie to determine wether the client is a regular one or from the API.  Still the API endpoint to update one parameter is not great. It might evolve in the futur. 
In any case, we'll update the documentation with the missing endpoints. 
Thanks for raising that up 👍
