### ISSUE TITLE
[FR] Notes auto-save

### ISSUE THREAD

**Issue by mag1c-synacktiv** [dfir-iris/iris-web#152]
**Is your feature request related to a problem? Please describe.**
Taking notes is an important part of the investigation process.
During an investigation, analysts tend to jump from one task to the other, forgetting that the note they were writing isn't actually saved. 
This can lead to data loss.

**Describe the solution you'd like**
Notes auto-save:
- Periodically every x minutes
- when the user stops writing
- when the user quits the note panel

**Additional context**
Many notes were lost due to the writer inattention ...

**Comment by Ektoplasma** [comment]
In addition, the CSRF token expires while the user is still in edition mode of a note, we should find a way to auto-refresh it.
