### ISSUE TITLE
Small documentation issues

### ISSUE THREAD

**Issue by c8y3** [dfir-iris/iris-web#159]
Here are a few typos found in the documentation pages:
* https://docs.dfir-iris.org/development/: The sub-branches of develop contains either => The sub-branches of develop contain either
* https://docs.dfir-iris.org/development/: An issue fixe => An issue fix
* https://docs.dfir-iris.org/development/: This ensure a smooth migration between versions => This ensures a smooth migration between versions
* https://docs.dfir-iris.org/development/environment/: Then Pycharm need to be setup with a dedicated environment, by adding a new configuration => Then Pycharm needs to be setup with a dedicated environment, by adding a new configuration
* https://docs.dfir-iris.org/development/environment/: To do so, the app docker need to be erased and rebuilt  => To do so, the app docker needs to be erased and rebuilt.
* https://docs.dfir-iris.org/development/code-tips/: IRIS does not defines a separate API for users => IRIS does not define a separate API for users
* https://docs.dfir-iris.org/development/code-tips/: It's often the page method itself except for modales => It's often the page method itself except for modals

It would be great to have acronyms link to some external explanatory page. For instance on page https://docs.dfir-iris.org/operations/modules/, EVTX could link to https://github.com/libyal/libevtx/blob/main/documentation/Windows%20XML%20Event%20Log%20(EVTX).asciidoc. Alternatively, a page with all acronym definitions would be nice. Such as VT: VirusTotal, MISP: Malware Information Sharing Project, IOC: Indicator Of Compromise, IR: Incident Response, DIM: DFIR IRIS Module... 
By the way, what is the meaning of DFIR-IRIS?

Lastly, on page https://docs.dfir-iris.org/operations/modules/, it would be nice to have "see Quick Start" be a link to the corresponding documentation page.

Thank you.

**Comment by c8y3** [comment]
Note: I didn't choose the bug template, as I thought this issue rather deserved the documentation label.

**Comment by whikernel** [comment]
@c8y3 thanks for the report. I'll close this one and open a new one in the documentation repo https://github.com/dfir-iris/iris-doc-src/issues. It will be easier for us to track.
