### ISSUE TITLE
[BUG] Error 500 when accessing IrisInitialClient

### ISSUE THREAD

**Issue by c8y3** [dfir-iris/iris-web#162]
**Describe the bug**
An error 500 is shown when accessing IrisInitalClient.

**To Reproduce**
1. Go to Advanced > Customers
2. Click on IrisInitialClient
4. See error 500

**Expected behavior**
No Error 500.

**Screenshots**
![IrisInitialClient_error_500](https://user-images.githubusercontent.com/25362953/211015696-6be243ab-49f8-46a5-b662-c04e92cba27f.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser Firefox
 - Version v2.0.0-beta-1

**Comment by whikernel** [comment]
Hi @c8y3  

Thanks for the report. This should be fixed in 31a561588de6271b78ad693abb668c47db1b9a97 (post v2.0.0-beta-1). It will be in the next beta release. 

Cheers
