### ISSUE TITLE
Some REST API documentation issues

### ISSUE THREAD

**Issue by c8y3** [dfir-iris/iris-web#165]
Here are a few issues with the REST API documentation.
* The example url provided in section "How to use" of https://docs.dfir-iris.org/operations/api/ has query parameter cid (http://localhost:8000/manage/cases/list?cid=1). But in the API documentation of endpoint [/manage/cases/list](https://docs.dfir-iris.org/_static/iris_api_reference_v1.0.3.html#operation/get-manage-cases-list), cid does not seem to be a query parameter.
* Field cid in the payload of [/manage/cases/add](https://docs.dfir-iris.org/_static/iris_api_reference_v1.0.3.html#operation/post-manage-cases-add) is indicated as required. This does not seem to be the case both from the request sample and an experimentation with v2.0.0-beta-1.
* It would be nice to have a response sample for endpoint [/case/export](https://docs.dfir-iris.org/_static/iris_api_reference_v1.0.3.html#operation/get-case-export)
* Endpoint /manage/customers/list to get the list of customers is not documented but seems to be working in version v2.0.0-beta-1
* Endpoint /manage/cases/{cid} to get a case seems not to be working in version v2.0.0-beta-1. It is not documented either, but it is present in the client. What should it be?

**Comment by whikernel** [comment]
@c8y3 thanks for the report. Could you please open it the issue in the documentation repo? 
https://github.com/dfir-iris/iris-doc-src 

Otherwise I'll copy this one and then close it. Let me know what you prefer.
