### ISSUE TITLE
[FR] - Allow editing of Case Title/Name

### ISSUE THREAD

**Issue by sjtrotter** [dfir-iris/iris-web#175]
*Please ensure your feature request is not already on the roadmap or associated with an issue. This can be checked [here](https://github.com/orgs/dfir-iris/projects/1/views/4).*

As far as I can tell this has not been submitted.

**Is your feature request related to a problem? Please describe.**

Sort of - after creating a case, I have not been able to find a way to change the name/title of the case.

**Describe the solution you'd like**

Add an edit button (or allow double-click) of the name/title of the case in order to edit the name.

**Describe alternatives you've considered**

none.

**Additional context**

none.

**Comment by whikernel** [comment]
Hi @sjtrotter 

Could you please tell us which version of IRIS you are using? This has been implemented in IRIS v2 Beta and will be soon ready for release. 

Cheers

**Comment by sjtrotter** [comment]
ah, gotcha! Looks like v1.4.5 is what we have installed.

**Comment by whikernel** [comment]
We'll close it since it's fixed in the next release then :) 
Fixed in #174
