### ISSUE TITLE
[BUG] docker-compose with default configuration does not start anymore

### ISSUE THREAD

**Issue by c8y3** [dfir-iris/iris-web#178]
**Describe the bug**
Since v2.0.0-beta-2, when starting totally afresh (no database, docker volumes are pruned), the docker-compose with the default configuration (.env is the same à .env.model), fails to start.

**To Reproduce**
1. copy .env.model to .env
2. docker-compose up
3. wait
4. See error in docker logs: 
    ```
    iriswebapp_app | 2023-01-30 14:08:31 :: INFO :: post_init :: run_post_init :: Creating first administrative user
    iriswebapp_db | 2023-01-30 14:08:31.977 UTC [59] LOG:  unexpected EOF on client connection with an open transaction
    iriswebapp_app | [2023-01-30 14:08:31 +0000] [7] [INFO] Shutting down: Master
    iriswebapp_app | [2023-01-30 14:08:31 +0000] [7] [INFO] Reason: Worker failed to boot.
    iriswebapp_worker | IRISwebapp is unavailable - sleeping
    iriswebapp_worker | IRISwebapp is unavailable - sleeping
    iriswebapp_worker | IRISwebapp is unavailable - sleeping
    ```

**Expected behavior**
The application should start without any error.

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Version:  v2.0.0-beta-2

**Additional context**
The error seems to go away when these two lines of the configuration file are uncommented:
```
#IRIS_ADM_PASSWORD=MySuperAdminPassword!
#IRIS_ADM_API_KEY=B8BA5D730210B50F41C06941582D7965D57319D5685440587F98DFDC45A01594
```
(However, this is not a satisfying solution)

Thank you!

**Comment by whikernel** [comment]
hi @c8y3 

Thank you! Indeed we identified the issue and it's already fixed in the upcoming beta 3. 
We let the issue open until the beta 3 is pushed just to ensure it's indeed fixed.  

The issue was lying in https://github.com/dfir-iris/iris-web/blob/bb3fe974eb529277efe82f16cc3b37f6fdd884ef/source/app/post_init.py#L556. We fixed and also added the possibility to change initial username and email of the admin. 

Cheers

**Comment by c8y3** [comment]
Thank you :+1: 
If you like, this bug could be a good occasion to automate a first non-regression test in github actions.

**Comment by sjtrotter** [comment]
I am also having this issue with a vanilla version of 1.4.5, following the instructions on the README.
After seeing this I tried checking-out v2.0.0-beta-3 and I am getting the same result still.

**Comment by whikernel** [comment]
Hi @sjtrotter 

I cannot replicate this with either v1.4.5 or v2.0.0. The `.env` (to copy from `.env.model`) provided in both versions should work out of the box.  Did you made any changes to it? 

Could you show us a screenshot of the errors you're having?

**Comment by sjtrotter** [comment]
The only changes made were the password and secret fields.

Here's screenshots of them all - IRIS errors :( https://imgur.com/a/K0hxaJY

The first one is a picture of the errors output after ` sudo docker compose up `

second is the logs of the nginx container with ` sudo docker logs -f xxxxxxxxx ` (where xxxxxxxxx is the container serial)

and third is the output of ` sudo docker ps ` showing the nginx unhealthy.

**Comment by whikernel** [comment]
@sjtrotter - Could you please send the whole logs traces from the docker. We're especially interested in the logs generated within the few seconds after the docker compose up.  The Web App fails to start for some reasons and that's why you have this message from Nginx.

**Comment by sjtrotter** [comment]
ah i see an error toward the top - i've copied the output from the docker-compose up from the first "sleeping" messages to the top and pasted here: https://pastebin.com/ZHn1sWc3

looks like the postgres password is not getting applied?

**Comment by whikernel** [comment]
Indeed the password isn't applied, most probably because the database was already initialized sometime in the past.  
Even if you delete the dockers and the repository, the database stays persistent. This allows to upgrade between versions without loosing your data. To do so we use named volumes.  

To fix your issue, the following steps should work (might need to adapt `docker compose` to `docker-compose`). 

```
# Will stop, delete all docker instances and volumes
docker compose down --volumes

# Ensure your .env is as you wish

# Rebuild the dockers 
docker compose build --no-cache 
docker compose up
```

Let us know how it goes

**Comment by sjtrotter** [comment]
ah - makes a lot of sense! I suspect on my initial install I had forgot to git checkout first, but I had already built and ctrl-c'd out. That's probably the reason why.

Very nice design - I would suggest finding a place to put those commands into the readme somewhere. Otherwise - I am running these now to find their effect.

I'm also curious - what's the best way to ensure that IRIS-web runs persistently across reboots that you use?

**Comment by whikernel** [comment]
I'm not sure if you started it twice again, but your database looks initialized again (see `iriswebapp_db | PostgreSQL Database directory appears to contain a database; Skipping initialization`) 

For the error, I suspect the env isn't set properly. Can you show it to us by redacting private info like passwords? Line 61 of your logs indicates IRIS is trying to connect to something else than just `db`.  It looks like part of the password is there. 

For the reboot, adding a service with systemd allows to ensure docker.service is up and running before spinning up IRIS.

**Comment by sjtrotter** [comment]
I think I put in my final edit just before you commented back - the issue was with the password, it had an `@` in it.

as far as the service - do you have an example service file? Or do you just enable the docker service and register these containers within it somehow? I can definitely google this just wanted to pose the question while I had you here.

**Comment by sjtrotter** [comment]
this should be my last post, just wanted to share what I did to enable this:

```
sudo systemctl enable docker
sudo vi /etc/systemd/system/iris-web.service
```
Contents:
```
[Unit]
Description=DFIR-IRIS Web
Requires=docker.service
After=docker.service

[Service]
Restart=always
ExecStart=/usr/bin/docker-compose -f /home/iris/iris-web/docker-compose.yml up
ExecStop=/usr/bin/docker-compose -f /home/iris/iris-web/docker-compose.yml down

[Install]
WantedBy=default.target
```
Then:
```
sudo systemctl daemon-reload
sudo systemctl enable iris-web
sudo systemctl start iris-web
```

and that should do it.

**Comment by whikernel** [comment]
Ah! So now it's working? 
For the @  it should work if you put your password within quotes so it's not interpreted. 

For the service, this is what we're using: 

```
[Unit]
Description=IRIS Docker Compose
Requires=docker.service
After=docker.service
StartLimitIntervalSec=0

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutStartSec=0
Restart=always
RestartSec=1
ExecStart=/usr/local/bin/docker-compose up -d
ExecStop=/usr/local/bin/docker-compose stop
WorkingDirectory=<<iris root directory>> 
User=<<iris user that can reach docker daemon>>

[Install]
WantedBy=multi-user.target
```

**Comment by whikernel** [comment]
@sjtrotter that's what we're doing indeed :)

**Comment by sjtrotter** [comment]
Ah nice! And yes it is working now, I did not have the password in quotes.

Does your version of the service keep logs after the initial run? And are you able to stop/restart it? I am not as familiar with the oneshot type.

**Comment by whikernel** [comment]
We're actually shipping the logs to a monitoring system with the integrate driver of docker so we don't have to take care of anything.  
  
This will be published in the documentation of IRIS v2, but you can already read the draft of the doc on this topic: https://github.com/dfir-iris/iris-doc-src/blob/access_control/docs/operations/logging.md

**Comment by sjtrotter** [comment]
nice, I'll look into something similar - till we work it out, I'll probly keep my version for now.

Are you guys planning on implementing that in the future? Could be another configuration option in .env, defaulted to local logs.

**Comment by whikernel** [comment]
@sjtrotter Implementing what in IRIS exactly? The ability to ship the logs?

**Comment by sjtrotter** [comment]
Yes, that's what I was talking about :)

**Comment by whikernel** [comment]
Probably not for the moment as it's pretty easy to ship the logs with the Docker drivers. But we keep it in mind!

**Comment by cr45hmurphy** [comment]
> this should be my last post, just wanted to share what I did to enable this:
> 
> ```
> sudo systemctl enable docker
> sudo vi /etc/systemd/system/iris-web.service
> ```
> 
> Contents:
> 
> ```
> [Unit]
> Description=DFIR-IRIS Web
> Requires=docker.service
> After=docker.service
> 
> [Service]
> Restart=always
> ExecStart=/usr/bin/docker-compose -f /home/iris/iris-web/docker-compose.yml up
> ExecStop=/usr/bin/docker-compose -f /home/iris/iris-web/docker-compose.yml down
> 
> [Install]
> WantedBy=default.target
> ```
> 
> Then:
> 
> ```
> sudo systemctl daemon-reload
> sudo systemctl enable iris-web
> sudo systemctl start iris-web
> ```
> 
> and that should do it.... lmk if there is a better way.

Would y'all be able to add this to the documentation? I am also willing to do so, I just didn't know if there's a certain format you want it to follow. 

This suggestion was extremely helpful to me, in ensuring that this started automatically at boot.

**Comment by whikernel** [comment]
Hi @cr45hmurphy 

Yes we can add this to the documentation indeed :) Thanks for the notice 👍
