### ISSUE TITLE
[FR] Add possibility to start with pre-activated modules

### ISSUE THREAD

**Issue by c8y3** [dfir-iris/iris-web#182]
**Is your feature request related to a problem? Please describe.**
In order to deploy IRIS in a fully automatic way, I would like a way to enable modules.
Today, some modules are pre-installed, some are pre-registered. But no module is enabled upfront. They must be manually enabled by the administrator.

**Describe the solution you'd like**
I would like to have a REST API endpoint to enable (and set the configuration) of modules.

**Describe alternatives you've considered**
Alternatively:
* there could be a way to inject the configuration of modules during the docker build
* the default configuration of modules could be loaded from file (and mounted in the docker)
* it could be decided that all pre-registered modules are enabled by default (but it wouldn't work for modules that require a configuration)

**Comment by legoguy1000** [comment]
There already is an API to enable and configure the modules. We do it with Ansible when we deploy Iris on kubernetes, we enable the MISP module and configure it to point the a local server.

**Comment by whikernel** [comment]
Hi @c8y3  

Indeed, the following endpoints can be used to enable and set configuration of modules: 

- POST `/manage/modules/enable/<int:module_id>`  :: No data 
- POST `/manage/modules/import-config/<int:module_id>` :: Data = a JSON similar to the one you have when clicking on `Export configuration`  

These endpoints are not documented yet. We'll add them in the documentation. 

Cheers

**Comment by c8y3** [comment]
Thank you. That is what I needed.
