### ISSUE TITLE
[BUG] Case count on Dashboard seems to be incorrect..?

### ISSUE THREAD

**Issue by sjtrotter** [dfir-iris/iris-web#194]
**Describe the bug**

On a fresh install, I closed the initial case demo case and then on the dashboard screen it is showing "Cases (open/all): 1 / 2" - it seems that the case is being counted twice possibly, and also not being counted as closed? Or, the count is possibly 1-based, and you need to subtract one from the results.

**To Reproduce**
1. Fresh install.
2. Close the initial case demo.
3. Load the Dashboard screen.

**Expected behavior**

The dashboard should list "Cases (open/all): 0/1" instead of "1/2"

**Screenshots**
![image](https://user-images.githubusercontent.com/33046718/218392474-eb3ea11b-993e-4e3d-87d0-a2fef6b2313c.png)

**Desktop (please complete the following information):**
 - OS: Win11 and also Fedora 36
 - Browser: Edge, and Firefox
 - Version: [e.g. 22]: 110.0.1587.41 (Official build) (64-bit), and 109.4 (64-bit)

**Additional context**
n/a

**Comment by whikernel** [comment]
Hi @sjtrotter 

This might be due to your current permissions. The cases count on the dashboard counts every cases in IRIS, independently of your current access rights. However, when you go in `Overview` or `Manage cases` you will see only the cases you have the right to see. Thus the count might differ. 

You can check it manually: 

```bash
# Connect to the DB docker 
docker exec -it iriswebapp_db /bin/bash

# Switch to postgres user and connect to db 
su postgres
psql 
\c iris_db;

# View all cases
select * from cases;
```

**Comment by sjtrotter** [comment]
I am trying to rebuild the iris-web to a clean install, but I can't seem to remove the database. (I can tell because of a few reasons - nothing changed on the dashboard, and the password I had changed, but it is unaffected.)

I have done ` sudo docker-compose build --no-cache ` as well as removed everything under /var/lib/docker (which I had thought would remove the hard drive of the database container) but all with no avail.

Is there some extra step I am missing to totally reset the iris build?

**Comment by whikernel** [comment]
@sjtrotter - Indeed, the database is not removed when you do a rebuild of the docker.  
We use a named docker volume to store the data of the database. This allows you to update between IRIS versions without loosing your data or worrying about database migration.  You can see this with `docker inspect <db_docker>`
 
If you want to totally reset IRIS, you need to issue the following commands. 

```
docker-compose down --volumes 
docker-compose build --no-cache 
docker-compose up -d
```

Also, we recommend adding the current user to the `docker` group to avoid having to run the commands with sudo

**Comment by sjtrotter** [comment]
got it, I was able to remove it with a series of docker commands, namely `docker volume rm $(docker volume ls -q)`

thanks for the group tip btw, very clean! sorry, I am not as familiar with docker (yet).
