### ISSUE TITLE
[FR] - Server Date Formatting

### ISSUE THREAD

**Issue by sjtrotter** [dfir-iris/iris-web#195]
*Please ensure your feature request is not already on the roadmap or associated with an issue. This can be checked [here](https://github.com/orgs/dfir-iris/projects/1/views/4).*

afaik it is not yet suggested.

**Is your feature request related to a problem? Please describe.**

n/a

**Describe the solution you'd like**

Allow administrators of the server to choose the date format used across IRIS.

**Describe alternatives you've considered**

n/a

**Additional context**

We are from the US - I noticed that the dates are using (I think?) European standard. Perhaps we could use ISO standard, or give the server admin the option to choose the date format on the server settings page.

**Comment by whikernel** [comment]
Hi! 

This has been implemented in IRIS v2.4.7. It now uses locales 👍
