### ISSUE TITLE
[BUG] Administrator wrong password 

### ISSUE THREAD

**Issue by IscarioteSXIII** [dfir-iris/iris-web#198]
Hi guys, i'm trying to install IRIS, but actually facing some issue

**Describe the bug**
2023-02-27 14:38:57 :: INFO :: post_init :: run_post_init :: Creating first administrative user
2023-02-27 14:38:57 :: WARNING :: post_init :: create_safe_admin :: >>> Administrator already exists

in my homelab, i set up an env variable with a 8 characters password (only capital letter , min and one number) but the password isnt recognized
![iris](https://user-images.githubusercontent.com/17250860/221595592-76eb1124-8f1d-40b8-89b5-ac4b3085c3ed.png)

**Desktop (please complete the following information):**
Debian11

**Additional context**
I killed all containers, clean the install, i even tried some docker system prune -, but issue is still there

**Comment by whikernel** [comment]
Hi  @IscarioteSXIII  

If you set the password in the .env then it needs to respect the default password policy which is 12 chars, at least one upper case, at least one lower case and at least one special char.  
We shall add this to the documentation. 

Cheers
