### ISSUE TITLE
iriswebapp not starting [BUG] 

### ISSUE THREAD

**Issue by polluxkj** [dfir-iris/iris-web#199]
**Describe the bug**
iriswebapp not starting

**To Reproduce**
1. standard installation steps
2.  error during boot 

**Expected behavior**
should start normally

**Screenshots**
![image](https://user-images.githubusercontent.com/6636959/223400782-aac0962b-9442-40d8-a489-6263cb4bc58e.png)
![image](https://user-images.githubusercontent.com/6636959/223401224-c587c50e-e33b-4be9-a5ef-fe87a2a2f694.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Version : 1.4.5 and v.2.0.0-beta3

**Additional context**
standard docker-compose.yml file - only passwords changed

**Comment by whikernel** [comment]
Hi @polluxkj 

It looks like the DB wasn't properly initialised. Maybe it was initiated before passwords where changed. 
Could you please do the following? 

- ensure your passwords in the .env are between quotes if they contains special chars 
- Run the following commands to start from scratch: 

docker compose down --volumes 
docker compose build
docker compose up 

Let me know if it helps
Cheers

**Comment by polluxkj** [comment]
Hi,
I have switched to debian 11.6 and it woks now.

**Comment by whikernel** [comment]
Hi @polluxkj  

It should also work on Ubuntu 22.04.2 LTS with a fresh install. We just tested and didn't face any issues. 
Please let us know if you want to try again on ubuntu, otherwise we'll close this issue. 

Thanks!
Cheers

**Comment by polluxkj** [comment]
May be it is a firewall configuration problem. I will play with Alma and/or Rocky as well.
Thank you

**Comment by whikernel** [comment]
Ok thanks, we'll then close the issue! 

Cheers
