### ISSUE TITLE
Add API endpoints "get list of analysis_status" and "get list of asset_type"

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#20]
Have an API endpoint that returns the list of defined analysis_status ("id", "value") and the list of defined asset_type ("id","value").

**Comment by whikernel** [comment]
Thanks @cudeso ! 

The first one analysis_status will be integrated in this issue https://github.com/dfir-iris/iris-web/issues/17,  tho not specified directly in the issue.   

The second one already exsists but was not reported in the documentation. 
You can make a GET on `manage/assettype/list` to retrieve them. 

I'll close this issue and create a new one referencing yours in the documentation repo to update.
