### ISSUE TITLE
Create a new module!

### ISSUE THREAD

**Issue by jdangosto** [dfir-iris/iris-web#201]
Hi!

How I can create a new module??

My idea is create a new module for connect with an App via API. (For example AbuseIP, etc.)

Thanks

**Comment by whikernel** [comment]
Hi @jdangosto  

You may read the following documentations : 

- https://docs.dfir-iris.org/development/modules/
- https://docs.dfir-iris.org/development/modules/quick_start/processor/ 
- https://blog.dfir-iris.org/deep_dives/iris_module_walkthough_p1/ 

Cheers!

**Comment by PiRomant** [comment]
It would be great if these links were in Add Module form.

**Comment by whikernel** [comment]
Links added. @jdangosto - can we close this issue or do you need any further help?

**Comment by jdangosto** [comment]
Of course! I Closed it
Thanks a lot.
