### ISSUE TITLE
Columns in the Manage Cases - Case List populating wrong data.[BUG] 

### ISSUE THREAD

**Issue by pemanuelsoc** [dfir-iris/iris-web#205]
The data filling in these columns seem to have the wrong column title. As you can see in the screenshot:

- The Description is listing the Customer.
- The Customer is listing the Open Date.
- The Open Date is listing the Closed Date.
![IrisIssue](https://user-images.githubusercontent.com/123008304/229903107-a9e0da74-f512-49e8-b8aa-b5e066796f54.PNG)

This is version 2.0.0

**Comment by whikernel** [comment]
Thanks for raising that up @pemanuelsoc . Indeed there's an issue with the table that an additional table header. It's fixed in https://github.com/dfir-iris/iris-web/commit/3f4587b27ea2e231b506ab75dbcb590e9dcf041a and will be integrated in the next patch 👍
