### ISSUE TITLE
[BUG] Minimized sidebar expanded before page finally loaded

### ISSUE THREAD

**Issue by PiRomant** [dfir-iris/iris-web#209]
**Describe the bug**
The minimized sidebar is expanded each time before the page is finally loaded. This generates a scaling animation after the data is loaded.

**To Reproduce**
Update a page with minimized sidebar.

**Expected behavior**
I would prefer that the sidebar doesn't expand at all, even when hovering over it. When hovering, display only the tooltip or tooltip menu.

**Screenshots**

https://user-images.githubusercontent.com/29551044/230776372-1ce07e9f-ccdd-4ced-ab07-8f0257eb8439.mp4

**Comment by whikernel** [comment]
Hi @PiRomant 

Indeed we noticed it - it's quite annoying, we'll fix it 👍

Cheers
