### ISSUE TITLE
Wrong variable types in API case/assets/add

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#22]
According to [https://dfir-iris.github.io/_static/iris_api_reference.html#operation/post-case-asset-add](https://dfir-iris.github.io/_static/iris_api_reference.html#operation/post-case-asset-add) the fields **asset_type_id** and **analysis_status_id** require a string. However the API returns
```"data": {"analysis_status_id": ["Not a valid integer."], "asset_type_id": ["Not a valid integer."]}```

Supplying integers in the POST results in a successful request.

Also see https://github.com/dfir-iris/iris-web/issues/20 and https://github.com/dfir-iris/iris-web/issues/21

**Comment by whikernel** [comment]
Thanks for the report ! 

That's a documentation issue on the API. I've created a new one in the documentation repo (https://github.com/dfir-iris/iris-doc-src/issues/7). I'll close this one.
