### ISSUE TITLE
[BUG] API key auth doesn't work with OIDC login method

### ISSUE THREAD

**Issue by legoguy1000** [dfir-iris/iris-web#220]
**Describe the bug**

**To Reproduce**
1. Setup OIDC login
2. Try to use API Key 
-    For example a POST request to /manage/users/update/1?cid=1 with "Authorization: Bearer XXXXXX" header set
3. Receive "Authentication required" 401 return

**Expected behavior**
API key authentication works

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu & Windows
 - Browser [e.g. chrome, safari] Ansible uri module and Mozilla

**Additional context**

It appears that the API key is validated and "current user" determined https://github.com/dfir-iris/iris-web/blob/0e59540b48d996de943c6afdddd4de9197ad5a48/source/app/views.py#L112.  However according to https://github.com/dfir-iris/iris-web/blob/0e59540b48d996de943c6afdddd4de9197ad5a48/source/app/util.py#L411, when OIDC login is enabled, it only checks the Browser flow login and doesn't check if "current user" is set.

The code should be updated to check for current user THEN normal OIDC.

**Comment by whikernel** [comment]
Hi @legoguy1000  

OIDC is currently not available (hence the lack of it in the documentation). This is something in progress that have been paused for a bit. We'll close this issue as this does not concern something we support at the moment 👍      

Cheers

**Comment by legoguy1000** [comment]
What do u mean not available? I'm using it in test on v2.0.1 right now.

**Comment by legoguy1000** [comment]
understood.  I may be able to assist with some changes, I just don't know how much time I have.  I think the reliance on Oauth2-proxy makes things more complicated than a built in method, but thats just my opinion.

**Comment by whikernel** [comment]
You are more than welcome to assist on any points I raised in my previous comment! 💯  
On future IRIS version with OIDC, we would provide a oauth2-proxy docker instance and the install would be almost as easy. We're ofc open to any idea to simplify the process and/or the code 👍

**Comment by legoguy1000** [comment]
So we deployed DFIR in kubernetes so we have to build our deployment yamls so not just plug and play but I'll see what I can do.
