### ISSUE TITLE
[BUG] Error toast notification split up

### ISSUE THREAD

**Issue by x-Thomas** [dfir-iris/iris-web#226]
**Describe the bug**
When adding a custom, additonal attribute defintion which is not in the valid format the error toast gets split up in multiple notification which makes it impossible to read.
This occurs whenver the Attribute definition is invalid.

**To Reproduce**
1. Log in with administrator permissions
2. Click on "Custom Attributes" in the menu "Advanced"
3. Select one of the listed objects
4. add invalid attribute definition, e.g.
```
{
    "Tab Name 1": {das}
}
```

**Expected behavior**
The error notification should be in a single  popup, in a readable format.

**Screenshots**
![iris_bug](https://user-images.githubusercontent.com/78706510/233858604-967a2329-abce-4e19-9826-8cfb5cee7534.gif)

**Comment by omarix** [comment]
Hi, 

I wanted to mention that I faced this issue with the version IRIS v2.0.0-beta-3. Also, I have noticed an issue when trying to display cases, and I have attached a screenshot to help illustrate the problem. 

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/12851334/234000698-f30bc827-b0d6-4512-90df-209680fb128b.png">
