### ISSUE TITLE
[FR] 24h time format

### ISSUE THREAD

**Issue by x-Thomas** [dfir-iris/iris-web#232]
Hey!

**Is your feature request related to a problem? Please describe.**
Currently the timeline edit view shows the datetime format in 12h format.
The 12h format is only used in a small amount of countries and its needs a second look on the AM/PM than just one on the timestamp.

![Timeline edit view](https://user-images.githubusercontent.com/78706510/235088665-2bd9e13c-f59b-4683-9a81-0dae00f0c5fd.png)

e.g. checking
**01:25:23 PM**
makes you check the hour first, then the "timeframe" AM or PM

If its written as 
**13:24:23** you directly know correct time.

And its mostly used by a country which counts height and weight in cheeseburgers.

**Describe the solution you'd like/alternatives you've considered**
The default could be set to 24 hour timeformat, otherwise it could be implemented as a user setting in their profile

**Comment by whikernel** [comment]
A change is being made on the development branch and the format the dates follows the host one 👍
