### ISSUE TITLE
[FR] Add permission to view customers details

### ISSUE THREAD

**Issue by AyoobAli** [dfir-iris/iris-web#235]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I suggest adding permission to allow users to view customers details. As the current permission this can be done only by giving the user admin permissions.

The reason for this is that if I'm adding custom attributes for the customers were I'm adding their contact details, Escalation matrix, and some additional information, And I want my analysts to be able to view those details I've added, but at the same time I don't want them to be able to edit and delete the customers

My suggestion is to do something similar to the alerts in the development branch, to add `customer_read`, `customer_write`, and `customer_delete`.

As I need this for the current setup I'm doing, I can work on this submit my code.

**Comment by whikernel** [comment]
Hi @AyoobAli 

Indeed this is something we planned to introduce gradually. The code to do so is already here, it's just a matter of adding the permissions in an enum and changing the corresponding routes wrappers 👍

**Comment by whikernel** [comment]
That have been added in the develop branch. I added `customers_read` and `customers_write` permissions 👍

**Comment by AyoobAli** [comment]
Thanks for the update @whikernel , I'm testing the beta branch now v2.1.0-beta-1.

Regarding the delete permission, I don't think it's that important now specially that the admin can do this, but it will be nice to have in the future.

**Comment by whikernel** [comment]
Will add it then 👍

**Comment by AyoobAli** [comment]
I've tested the customer permission, and it looks like it's working fine. Great work.

I have a suggestion, currently when the user with read only access visit the customer page, he have to click on "Edit" to view the customer custom attributes, and if he clicks save, he will get a message that he doesn't have permission.

What if we add the custom attributes tabs in the customer profile page to be as text only, "like the customer name, and SLA" and hide the "Edit" button when the user doesn't have write access.

This is not an important update, it's only cosmetic, so maybe this is something we can add to the end of the road map.
And I believe we can close this issue.

**Comment by whikernel** [comment]
Indeed @AyoobAli - the only issue we have at the moment is the way the UI is built. We'll need to switch at some point to a more modern and proper way. We'll probably add these when we switch 👍
