### ISSUE TITLE
[BUG] LDAP authentication does not support LDAPS without TLS client authentication

### ISSUE THREAD

**Issue by heck-gd** [dfir-iris/iris-web#236]
We're currently trying to use LDAP authentication with IRIS and noted the following things:
1. The documentation and code talks about "LDAP server certificate", "LDAP_SERVER_CERTIFICATE", etc. - this is quite misleading, because this does not in fact configure a server certificate (typically I would understand this to be a CA certificate to verify the server's identity). It configures a TLS client certificate that is offered to the server as part of TLS client authentication.
2. Our LDAP server uses LDAPS, but we do not issue client certificates. It is currently impossible to use IRIS with such a configuration, because it will either not connect via `ldaps://`, or if you enable SSL, it will refuse to start because of missing certificates/keys.

**Comment by whikernel** [comment]
Hi @heck-gd 

Indeed this is something that we identified and has just been resolved (hopefully) today in the https://github.com/dfir-iris/iris-web/tree/develop branch. 
It will be pushed into the next release 👍
