### ISSUE TITLE
[BUG] "Permission denied" for search as an Analysts (Search is OK for administrators)

### ISSUE THREAD

**Issue by juadde** [dfir-iris/iris-web#237]
**Describe the bug**
Search is unavailable for analysts (so either it is intended and then why the user should be able to access this menu - or maybe the search should be configured by another mean?)

**To Reproduce**
1. Launch IRIS
2. Create a user
3. Put the user in "Analyst" group
4. Give full rights on the case to the "Analyst" group
5. Try to search (e.g. with the wildcard)
6. See red popup on the bottom left with"Permission denied"

(One can also login to the demo website and try to perform a search when being a standard user)

**Expected behavior**
Search should be able to work as it does for administrator.

**Screenshots**
![image](https://user-images.githubusercontent.com/29175532/235705710-ee42a4ba-2dcf-4ca6-b99a-3b4e760555b2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser: Firefox 112

**Additional context**
I guess search should be working for analysts too, please let me know if I misunderstood this feature.

**Comment by whikernel** [comment]
Hi @juadde 

That was on purpose but indeed it depends on the use cases. I added a new permissions `search_across_cases` so anyone can choose :) 
It will be pushed in the next release.

**Comment by juadde** [comment]
Hi @whikernel, thanks, do you intend to hide the tab menu if the right is not set?
