### ISSUE TITLE
Wrong field name when fetching PG password

### ISSUE THREAD

**Issue by Ektoplasma** [dfir-iris/iris-web#24]
The field name used to get the PG Password when not set by the environment variable is wrong: https://github.com/dfir-iris/iris-web/blob/develop/source/app/configuration.py#L42

`PG_PASSWD_ = os.environ.get('DB_PASS', config.get('POSTGRES', 'PG_ACCOUNT'))`

'PG_ACCOUNT' should be 'PG_PASSWD' as specified in https://github.com/dfir-iris/iris-web/blob/develop/source/app/config.model.ini

**Comment by whikernel** [comment]
Fixed in https://github.com/dfir-iris/iris-web/commit/c7f4c791b625c912ee8416a42fedadd3f541be44
