### ISSUE TITLE
[BUG] docker-compose build fails - Additional properties are not allowed

### ISSUE THREAD

**Issue by CdtDelta** [dfir-iris/iris-web#256]
**Describe the bug**
I'm just testing out iris-web on my Ubuntu 18.04 laptop with docker. When I get to the docker-compose build step it throws an error:

ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.iris_backend value Additional properties are not allowed ('name' was unexpected)
networks.iris_frontend value Additional properties are not allowed ('name' was unexpected)

**To Reproduce**
1)  Clone the iris-web repository
```
git clone https://github.com/dfir-iris/iris-web.git
cd iris-web
```

2) Checkout to the last tagged version 
`git checkout v2.2.1`

3) Copy the environment file 
`cp .env.model .env`

4) Build the dockers
`docker-compose build`

**Expected behavior**
I expect the docker-compose build command to complete without errors (I'm not sure what it will return)? I didn't make any changes to the .env file since I'm just testing it. From what I saw in the documentation that really only needs to be edited when it's going to be used for "production."

**Desktop (please complete the following information):**
OS: Ubuntu 18.04 (5.4.0-149-generic)

**Comment by whikernel** [comment]
Hi @CdtDelta 

This is probably related to an outdated version of docker. Could you please check that you are running the last version available and update accordingly? 

Cheers

**Comment by CdtDelta** [comment]
Here's what I'm running:

[27-May-23 12:34:18] HOST:~$ docker -v
Docker version 24.0.2, build cb74dfc

**Comment by whikernel** [comment]
Did you try with "docker-compose" or "docker compose"?

**Comment by CdtDelta** [comment]
Per the instructions I did docker-compose. Should I try just "docker compose"?

**Comment by whikernel** [comment]
Yes kindly try with `docker compose` if the command is available to you.

**Comment by CdtDelta** [comment]
Ok that's all it was. Sorry about that.
