### ISSUE TITLE
Shuffle integration 

### ISSUE THREAD

**Issue by tboy-hacker** [dfir-iris/iris-web#258]
Good day love the project so much to the point I made a video about it on my socials could you add integrations with opencti in the  modules section and shuffle for automation purposes

**Comment by whikernel** [comment]
Hi @tboy-hacker 

OpenCTI is on the roadmap, it will be integrated at some point 👍  
For Shuffle, it already exists an integration https://shuffler.io/apps/200c350c003b48530ad3f5edcf688e86?queryID=4f48273e8f64eec97fadf3a12595677a.  
I think it's not up to date, but Shuffle can consume OpenAPI specification so it's only a matter of uploading the specification published here: https://docs.dfir-iris.org/operations/api/ 👍  

Cheers!

**Comment by tboy-hacker** [comment]
I have been trying to integrate shuffle with the API or hook but it is not working for me

**Comment by tboy-hacker** [comment]
What is the GitHub link for the shuffle integration will love to contribute

**Comment by whikernel** [comment]
It's the link I posted above :) 

https://shuffler.io/apps/200c350c003b48530ad3f5edcf688e86?queryID=4f48273e8f64eec97fadf3a12595677a 

What it not working with Shuffle? 
Shuffle is like a bridge between different tools using their APIs. So if it's normally a matter of making Shuffle sending data following the IRIS API specification, depending of what you want to achieve.

**Comment by tboy-hacker** [comment]
Thank you so much for the reply I'm reading the documentation now what is the meaning of the API key is to be use space=skip

**Comment by tboy-hacker** [comment]
Sorry to ask but I don't want to disturb the team I am having troubles with the query in the shuffle section and I don't know how to use it and also is it outdated I really need help as fast as you guys can respond I have a project to finish and I want to recommend I iris to my friends

**Comment by whikernel** [comment]
Hi @tboy-hacker 

We would need much more information in order to help you: 

- The requests you are making, including the endpoints and the data sent 
- What you are trying to achieve, etc 

I'm also not sure to understand your question on the API Key.

**Comment by tboy-hacker** [comment]
I'm trying to use the shuffle integration but not working for me with the live demo of iris

**Comment by whikernel** [comment]
If I'm not mistaken the default Shuffle integration is compatible with API 1.0.1. Current demo is 2.0.1, so there will be issues. 
You need to import the new API specification in Shuffle. 

We also need way more details on what's wrong. Errors, stack traces etc. Otherwise it's really hard to help you 

Cheers

**Comment by tboy-hacker** [comment]
I don't want to disturb the roadmap at all but is it possible for you guys to make demo videos for the project because someone already made it but it's the old version of the project

https://youtu.be/ZUtTxZJKJXs
https://youtu.be/XXyIv_aes4w
