### ISSUE TITLE
Bug when creating a new case

### ISSUE THREAD

**Issue by fvlasicbee** [dfir-iris/iris-web#269]
I have just installed the recent version of IRIS and I am getting the following error when creating a new case:

iriswebapp_nginx     | 2023/06/19 15:11:07 [info] 9#9: *4981 client 127.0.0.1 closed keepalive connection
iriswebapp_app       | 2023-06-19 15:11:08 :: ERROR :: manage_cases_routes :: api_add_case :: 'NoneType' object has no attribute 'state_id'
iriswebapp_app       | 2023-06-19 15:11:08 :: ERROR :: manage_cases_routes :: api_add_case :: Traceback (most recent call last):
iriswebapp_app       |   File "/iriswebapp/app/blueprints/manage/manage_cases_routes.py", line 317, in api_add_case
iriswebapp_app       |     case.state_id = get_case_state_by_name('Opened').state_id
iriswebapp_app       | AttributeError: 'NoneType' object has no attribute 'state_id'

After pressing "Save" there is no error message on the web interface, only this log in the terminal.

I am running this on my Apple M2 Macbook Pro.

Many thanks.

**Comment by whikernel** [comment]
@fvlasicbee  - Could you please try to pull and checkout on v2.2.3 again? 
There was a typo preventing the proper creation of a case.
