### ISSUE TITLE
Installing DFIR IRIS on AWS Ubuntu 22.04

### ISSUE THREAD

**Issue by Vinothkumarcr7** [dfir-iris/iris-web#271]
Hi Team,

I have setup a Ubuntu machine in AWS and installed a Docker on it. And i followed the steps provided in the below IRIS document.

https://docs.dfir-iris.org/getting_started/

I have successfully completed the installation. However , i need to access the IRIS console from my local machine's browser,  IRIS is hosted on the AWS. I have allowed the inbound AWS security rule for the Ubuntu instance over 8000 port as well.

Initially , we are trying to test different use cases and later planning to add more options on it. Can you please help on what network changes to add so that i can access the IRIS console locally in browser and other analyst can access the same from their machines.

ubuntu@ip-172-31-30-38:~$ netstat -tulp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 localhost:postgresql    0.0.0.0:*               LISTEN      -                   
tcp        0      0 localhost:8000          0.0.0.0:*               LISTEN      -                   
tcp        0      0 ip-172-31-30-38.ec2:bbs 0.0.0.0:*               LISTEN      -                   
tcp        0      0 localhost:7199          0.0.0.0:*               LISTEN      -                   
tcp        0      0 localhost:33303         0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:https           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN      -                   
tcp        0      0 ip-172-31-30-38.ec:9042 0.0.0.0:*               LISTEN      -                   
tcp        0      0 localhost:domain        0.0.0.0:*               LISTEN      -                   
tcp6       0      0 localhost:38547         [::]:*                  LISTEN      -                   
tcp6       0      0 ip-172-31-30-38.ec:9300 [::]:*                  LISTEN      -                   
tcp6       0      0 [::]:https              [::]:*                  LISTEN      -                   
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      -                   
tcp6       0      0 ip-172-31-30-38.ec:9200 [::]:*                  LISTEN      -                   
tcp6       0      0 [::]:9000               [::]:*                  LISTEN      -                   
tcp6       0      0 [::]:9001               [::]:*                  LISTEN      -                   
udp        0      0 localhost:domain        0.0.0.0:*                           -                   
udp        0      0 ip-172-31-30-38.:bootpc 0.0.0.0:*                           -                   
udp        0      0 localhost:323           0.0.0.0:*                           -                   
udp6       0      0 ip6-localhost:323       [::]:*                              -                   

------------------

ubuntu@ip-172-31-30-38:~/iris-web$ cat .env
# -- NGINX
SERVER_NAME=iris.app.dev
KEY_FILENAME=iris_dev_key.pem
CERT_FILENAME=iris_dev_cert.pem

# -- DATABASE
POSTGRES_USER=postgres
POSTGRES_PASSWORD=__MUST_BE_CHANGED__
POSTGRES_ADMIN_USER=raptor
POSTGRES_ADMIN_PASSWORD=__MUST_BE_CHANGED__
POSTGRES_DB=iris_db

POSTGRES_SERVER=db
POSTGRES_PORT=5432

# -- IRIS
DOCKERIZED=1
IRIS_SECRET_KEY=AVerySuperSecretKey-SoNotThisOne
IRIS_SECURITY_PASSWORD_SALT=ARandomSalt-NotThisOneEither
IRIS_UPSTREAM_SERVER=app
IRIS_UPSTREAM_PORT=8000

# -- WORKER
CELERY_BROKER=amqp://rabbitmq

# -- AUTH
IRIS_AUTHENTICATION_TYPE=local
## optional
#IRIS_ADM_PASSWORD=MySuperAdminPassword!
#IRIS_ADM_API_KEY=B8BA5D730210B50F41C06941582D7965D57319D5685440587F98DFDC45A01594
#IRIS_ADM_EMAIL=admin@localhost
#IRIS_ADM_USERNAME=administrator
# requests the just-in-time creation of users with ldap authentification (see https://github.com/dfir-iris/iris-web/issues/203)
#IRIS_AUTHENTICATION_CREATE_USER_IF_NOT_EXIST=True
# the group to which newly created users are initially added, default value is Analysts
#IRIS_NEW_USERS_DEFAULT_GROUP=

# -- FOR LDAP AUTHENTICATION
#IRIS_AUTHENTICATION_TYPE=ldap
#LDAP_SERVER=127.0.0.1
#LDAP_AUTHENTICATION_TYPE=SIMPLE
#LDAP_PORT=3890
#LDAP_USER_PREFIX=uid=
#LDAP_USER_SUFFIX=ou=people,dc=example,dc=com
#LDAP_USE_SSL=False
# base DN in which to search for users
#LDAP_SEARCH_DN=ou=users,dc=example,dc=org
# unique identifier to search the user
#LDAP_ATTRIBUTE_IDENTIFIER=cn
# name of the attribute to retrieve the user's display name
#LDAP_ATTRIBUTE_DISPLAY_NAME=displayName
# name of the attribute to retrieve the user's email address
#LDAP_ATTRIBUTE_MAIL=mail
#LDAP_VALIDATE_CERTIFICATE=True
#LDAP_TLS_VERSION=1.2
#LDAP_SERVER_CERTIFICATE=
#LDAP_PRIVATE_KEY=
#LDAP_PRIVATE_KEY_PASSWORD=

# -- LISTENING PORT
INTERFACE_HTTPS_PORT=443

 ---------------

ubuntu@ip-172-31-30-38:~/iris-web$ sudo docker container ls
CONTAINER ID   IMAGE                          COMMAND                  CREATED       STATUS                PORTS                                                                  NAMES
3ebedeeafd48   iriswebapp_app:v2.2.3          "./wait-for-irisweba…"   4 days ago    Up 4 days                                                                                    iriswebapp_worker
eac8d3dec04f   iriswebapp_nginx:v2.2.3        "/entrypoint.sh"         4 days ago    Up 4 days (healthy)   80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                          iriswebapp_nginx
558f776b1f5c   iriswebapp_app:v2.2.3          "nohup ./iris-entryp…"   4 days ago    Up 4 days             127.0.0.1:8000->8000/tcp                                               iriswebapp_app
192ec9dcfe66   iriswebapp_db:v2.2.3           "docker-entrypoint.s…"   4 days ago    Up 4 days             127.0.0.1:5432->5432/tcp                                               iriswebapp_db
aa59cb56db2f   rabbitmq:3-management-alpine   "docker-entrypoint.s…"   13 days ago   Up 8 days             4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 15691-15692/tcp, 25672/tcp   iriswebapp_rabbitmq

-----------------------
In Nginx conf file , i have modified the server access to below from default. (added 0.0.0.0 before $ symbol)
 **listen          0.0.0.0:${INTERFACE_HTTPS_PORT} ssl;**

ubuntu@ip-172-31-30-38:~/iris-web/docker/nginx$ cat nginx.conf 
#  IRIS Source Code
#  Copyright (C) 2021 - Airbus CyberSecurity (SAS)
#  ir@cyberactionlab.net
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 3 of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    map $request_uri $csp_header {
        default "default-src 'self' https://analytics.dfir-iris.org; script-src 'self' 'unsafe-inline' https://analytics.dfir-iris.org; style-src 'self' 'unsafe-inline';";
    }
    include /etc/nginx/mime.types;

    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log main;
    error_log   /var/log/nginx/error.log debug;

    server_tokens off;

    sendfile    on;
    tcp_nopush  on;
    tcp_nodelay on;

    types_hash_max_size             2048;
    types_hash_bucket_size          128;
    proxy_headers_hash_max_size     2048;
    proxy_headers_hash_bucket_size  128;
    proxy_buffering                 on;
    proxy_buffers                   8 16k;
    proxy_buffer_size               4k;

    client_header_buffer_size   2k;
    large_client_header_buffers 8 64k;
    client_body_buffer_size     64k;
    client_max_body_size        100M;

    reset_timedout_connection   on;
    keepalive_timeout           90s;
    client_body_timeout         90s;
    send_timeout                90s;
    client_header_timeout       90s;
    fastcgi_read_timeout        90s;
    # WORKING TIMEOUT FOR PROXY CONF
    proxy_read_timeout          90s;
    uwsgi_read_timeout          90s;

    gzip off;
    gzip_disable "MSIE [1-6]\.";

    # FORWARD CLIENT IDENTITY TO SERVER
    proxy_set_header    HOST                $http_host;
    proxy_set_header    X-Forwarded-Proto   $scheme;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

    # FULLY DISABLE SERVER CACHE
    add_header          Last-Modified $date_gmt;
    add_header          'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    if_modified_since   off;
    expires             off;
    etag                off;
    proxy_no_cache      1;
    proxy_cache_bypass  1;

    # SSL CONF, STRONG CIPHERS ONLY
    ssl_protocols               TLSv1.2 TLSv1.3;

    ssl_prefer_server_ciphers   on;
    ssl_certificate             /www/certs/${CERT_FILENAME};
    ssl_certificate_key         /www/certs/${KEY_FILENAME};
    ssl_ecdh_curve              secp521r1:secp384r1:prime256v1;
    ssl_buffer_size             4k;

    # DISABLE SSL SESSION CACHE
    ssl_session_tickets         off;
    ssl_session_cache           none;

    access_log /var/log/nginx/audit_platform_access.log main;
    error_log  /var/log/nginx/audit_platform_error.log debug;

    server {
        listen          0.0.0.0:${INTERFACE_HTTPS_PORT} ssl;
        server_name     ${SERVER_NAME};
        root            /www/data;
        index           index.html;
        error_page      500 502 503 504  /50x.html;

        add_header Content-Security-Policy $csp_header;
        
        # SECURITY HEADERS
        add_header X-XSS-Protection             "1; mode=block";
        add_header X-Frame-Options              DENY;
        add_header X-Content-Type-Options       nosniff;
        # max-age = 31536000s = 1 year
        add_header Strict-Transport-Security    "max-age=31536000: includeSubDomains" always;
        add_header Front-End-Https              on;

        location / {
            proxy_pass  http://${IRIS_UPSTREAM_SERVER}:${IRIS_UPSTREAM_PORT};

            location ~ ^/(manage/templates/add|manage/cases/upload_files) {
                keepalive_timeout           10m;
                client_body_timeout         10m;
                send_timeout                10m;
                proxy_read_timeout          10m;
                client_max_body_size        0M;
                proxy_request_buffering off;
                proxy_pass  http://${IRIS_UPSTREAM_SERVER}:${IRIS_UPSTREAM_PORT};
            }

            location ~ ^/(datastore/file/add|datastore/file/add-interactive) {
                keepalive_timeout           10m;
                client_body_timeout         10m;
                send_timeout                10m;
                proxy_read_timeout          10m;
                client_max_body_size        0M;
                proxy_request_buffering off;
                proxy_pass  http://${IRIS_UPSTREAM_SERVER}:${IRIS_UPSTREAM_PORT};
            }
        }
        location /socket.io {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_pass http://${IRIS_UPSTREAM_SERVER}:${IRIS_UPSTREAM_PORT}/socket.io;
        }

        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}

Please let me know if you need any other details.

Many thanks
Vinoth

**Comment by whikernel** [comment]
Hi @Vinothkumarcr7 

So you are able to access the interface on port 443 of the host machine but you want to access it also on 8000? 
Jfy The default listening port is https/443 and 8000 is not exposed on the host interfaces. 

Cheers

**Comment by Vinothkumarcr7** [comment]
Hi @whikernel ,

Thanks a lot !

I can able to access the console over port 4from my browser. However , i am unable to find the password in the logs , please refer the below for your reference.

iriswebapp_worker    | 2023-06-28 06:21:44 :: INFO :: post_init :: run_post_init :: Creating initial authorisation model
iriswebapp_worker    | 2023-06-28 06:21:44 :: INFO :: post_init :: run_post_init :: Creating first administrative user
iriswebapp_worker    | 2023-06-28 06:21:44 :: WARNING :: post_init :: create_safe_admin :: >>> Administrator already exists
iriswebapp_worker    | 2023-06-28 06:21:44 :: INFO :: post_init :: run_post_init :: Registering default modules


Can you please help to identify the default credentials ?


Many thanks

**Comment by whikernel** [comment]
Hi @Vinothkumarcr7  

The credentials are set only the very first time you start IRIS and display in the logs. You probably run IRIS multiple times hence the message you shown. 
You can either try to change the administrator password by following this: 
https://docs.dfir-iris.org/operations/access_control/authentication/#changing-a-lost-password

Or since this is a new instance, reset it from scratch.  
```
docker compose down --volumes 
docker compose up 
```

Let me know how it goes.

**Comment by whikernel** [comment]
Hi! Please reopen the issue if you still have problem 👍
