### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by st3l1n** [dfir-iris/iris-web#275]
**Describe the bug**
When getting virustotal report permanent link doesn't go to virustotal

**To Reproduce**
1. Go to IOC
2. Click on Edit
3. Click "Get VT insight"
4. Go to VT Report tab
5. Click on pemalink
6. redirect to iris not to vt =(

**Expected behavior**
Redirect to VT page

**Screenshots**
[image](https://imgur.com/a/gPtuBLO)

In screenshot I navigated cursor on permalink

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox, Vivaldi
 - Version latest, latest

**Comment by Matthijsy** [comment]
This is actually not a bug of IRIS, but of the iris-vt-module. I experienced the same, and have just created a PR to fix the issue.

https://github.com/dfir-iris/iris-vt-module/pull/4

**Comment by whikernel** [comment]
Thanks @Matthijsy  - we'll integrate the change in the next patch 👍
