### ISSUE TITLE
[BUG] Error when trying to change user password

### ISSUE THREAD

**Issue by fvlasicbee** [dfir-iris/iris-web#282]
**Describe the bug**
Error when trying to change user password.

**To Reproduce**
1. Go to My Settings
2. Click on 'Change password'
3. Enter new password (2x)

**Expected behavior**
Password change

![Screenshot 2023-07-24 at 16 17 44](https://github.com/dfir-iris/iris-web/assets/129166158/2d45f0de-b4b4-4ee8-9142-8ca96e324533)

**Comment by whikernel** [comment]
Hi @fvlasicbee 

Could you please indicate which version of IRIS you are using? 

Cheers

**Comment by whikernel** [comment]
This was fixed in v2.3.0 and later 👍  
https://docs.dfir-iris.org/changelog/#v230-july-09-2023

**Comment by fvlasicbee** [comment]
Oh, great, I wasn't aware you are pushing updates so often :) Sorry, Thanks!
