### ISSUE TITLE
[BUG] postgresql connect error 

### ISSUE THREAD

**Issue by kim-namjin** [dfir-iris/iris-web#284]
**Describe the bug**
Error using special characters when setting id, pw in Postgresql. Because of the % character

**To Reproduce**
1. modify the .env file 
   POSTGRES_PASSWORD=test12%40!
   POSTGRES_ADMIN_PASSWORD=test1212%40!

2. docker compose up -d

**Expected behavior**
An error occurs when accessing postgresql.

**Screenshots**
![images  31](https://github.com/dfir-iris/iris-web/assets/68531772/e994129d-ec08-476e-841e-d53896b89d4e)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome

Changes in source/app/configuration.py (line 167)

# Fetch the values
PG_ACCOUNT_ = config.load('POSTGRES', 'USER').replace('%', '%%')
PG_PASSWD_ = config.load('POSTGRES', 'PASSWORD').replace('%', '%%')
PGA_ACCOUNT_ = config.load('POSTGRES', 'ADMIN_USER').replace('%', '%%').replace('%', '%%')
PGA_PASSWD_ = config.load('POSTGRES', 'ADMIN_PASSWORD').replace('%', '%%')

**Comment by m-terlinde** [comment]
Have you tried to enquote the value like this?

```
POSTGRES_PASSWORD="test12%40!"
POSTGRES_ADMIN_PASSWORD="test1212%40!"
```

**Comment by kim-namjin** [comment]
Hi

PG_ACCOUNT_ = config.load('POSTGRES', 'USER').replace('%', '%%')
PG_PASSWD_ = config.load('POSTGRES', 'PASSWORD').replace('%', '%%')
PGA_ACCOUNT_ = config.load('POSTGRES', 'ADMIN_USER').replace('%', '%%').replace('%', '%%')
PGA_PASSWD_ = config.load('POSTGRES', 'ADMIN_PASSWORD').replace('%', '%%')

I think I got this part wrong.

First of all, in the .env file 
POSTGRES_PASSWORD="test12%40!"
POSTGRES_ADMIN_PASSWORD="test1212%40!"
I changed it to this and recreated the Docker Container to test run it.

At this point, it seems that the  % characters from urlencoding special characters causes an error.

If i set the password to plain text without % characters, it works fine.

When running PASSWORD with the following special characters, an error occurs.
"test12%40!"
'test12%40!
'test12%%40!'
