### ISSUE TITLE
[FR] Bulk status updates for Alerts, Cases

### ISSUE THREAD

**Issue by kim-namjin** [dfir-iris/iris-web#289]
**Is your feature request related to a problem? Please describe.**
I want to update the status of multiple Alerts and cases created in IRIS at once.

**Describe the solution you'd like**
I would like to add a check box on the left side of the Alert, Case list and update the status of the checked alert, case at once.

**Additional context**
Currently, my system generates more than 1000 alerts per day, but changing the status value of each one of them is too laborious.

**Comment by whikernel** [comment]
Hi @kim-namjin 

When you are on the alert page, you can press `Select` at the top of the page, and then select the alerts you want to bulk manage. 
You can also select all displayed alerts. You can as well increase the number of alerts per page.  

<img width="1484" alt="image" src="https://github.com/dfir-iris/iris-web/assets/74464599/e4b220e4-1258-4ac9-9b37-0a0bf9f4dd1d">

Is that what you are looking for? 

Cheers

**Comment by kim-namjin** [comment]
Hi whikernel

Yes, you are correct.
This is the functionality I was looking for.

I didn't think this feature existed!

regards
