### ISSUE TITLE
[BUG] Alerts page breaking when an Alert is assigned to a User

### ISSUE THREAD

**Issue by taylorwalton** [dfir-iris/iris-web#293]
Hey Team,

I have noticed what appears to be a bug regarding assigning a user to an Alert in version `2.3.2`.

This issue is occurring infrequently which has made it difficult to troubleshoot and collect evidence but I will provide as much details as I have so far. 

When trying to view the Alerts page, sometimes it gets stuck in this loading phase but looking at the API request, data is being retrieved:

![image](https://github.com/dfir-iris/iris-web/assets/111797488/f3afc47e-6dcc-41a8-999a-f1c6884de021)

I also see the below error in my browser which points to the `common.js` file:

![image](https://github.com/dfir-iris/iris-web/assets/111797488/49cc17d1-f124-46b5-9911-f6c0e9f45a98)

![image](https://github.com/dfir-iris/iris-web/assets/111797488/f6ff86cb-fab2-4907-93ec-f74bbb602a21)

I've noticed that this only sometimes happens...for example, when I remove all the alerts and start to load some new ones in, the page details them as expected...but over time this error will randomly occur.

Looking at the common.js file where the error is occurring it looks like the error is related to the avatar of the user assigned to the alert?

```
function get_avatar_initials(name, small, onClickFunction, xsmall) {
    let av_size = small ? 'avatar-sm' : 'avatar';
    av_size = xsmall ? 'avatar-xs' : av_size;
    const onClick = onClickFunction ? `onclick="${onClickFunction}"` : '';

    if (avatarCache[name] && avatarCache[name][small ? 'small' : 'large']) {
        return `<div class="avatar ${av_size}" title="${name}" ${onClick}>
            ${avatarCache[name][small ? 'small' : 'large']}
        </div>`;
    }

    const initial = name.split(' ');
    let snum;

    if (initial.length > 1) {
        snum = initial[0][0].charCodeAt(0) + initial[1][0].charCodeAt(0);
    } else {
        snum = initial[0][0].charCodeAt(0);
    }

    const initials = initial.map(i => i[0].toUpperCase()).join('');
    const avatarColor = get_avatar_color(snum);

    const avatarHTMLin = `<span class="avatar-title avatar-iris rounded-circle" style="background-color:${avatarColor}; cursor:pointer;">${initials}</span>`
    const avatarHTMLout = `<div class="avatar ${av_size}" title="${name}" ${onClick}>
        ${avatarHTMLin}
    </div>`;

    if (!avatarCache[name]) {
        avatarCache[name] = {};
    }
    avatarCache[name][small ? 'small' : 'large'] = avatarHTMLin;

    return avatarHTMLout;
}
```

One theory of mine is that there is a character (maybe a special character?) that is apart of a username and when that user is assigned to an Alert, that is breaking the page? Could also help explain the infrequency of this issue.

The usernames of users created within IRIS all follow a firstname followed by a lastname. The only `special character` based on the usernames in the platform is a `.` where the last name is `B.K`. Could not be a factor at all but wanted to run my theory by you guys.

Thanks in advance! 

Taylor

**Comment by whikernel** [comment]
@taylorwalton 

Thanks for the issue! Can you check if the user has a space in its username at the end? 
Looking at the code, initial[1][0] will be undefined if the name is like "Michael ", because there is a split on the space.   

If so, then a quick fix is to remove the space in the username. We'll patch the code in the next release 👍

**Comment by taylorwalton** [comment]
Hey @whikernel ,

Thanks for the feedback! 

Indeed that is the issue. I was able to successfully replicate the issue:

![image](https://github.com/dfir-iris/iris-web/assets/111797488/9073737a-6e1c-496a-9d83-3f29520e46b1)


![image](https://github.com/dfir-iris/iris-web/assets/111797488/7ba4d356-bf7c-4e61-bf2e-8ac35ef0de28)

Thanks again!
