### ISSUE TITLE
[FR]Requires a session timeout for the account.

### ISSUE THREAD

**Issue by kim-namjin** [dfir-iris/iris-web#297]
There is no session timeout setting in your current account settings.
This is a problem because the session lasts indefinitely.

We need a timeout setting for sessions.

**Comment by wonhee0410** [comment]
> Hi @kim-namjin
> 
> The session tokens have a 24h timeout. However each time your are browsing on the pages, you're essentially getting a new one, hence pushing the 24h further and further. Once you stop using IRIS for 24h, you'll have to login again.

Hi,

Can I manually change the session timeout to 15 minutes to satisfy the regulation of company ?

Thank you.

**Comment by whikernel** [comment]
Hi! 

It is by setting the .env with `IRIS_SESSION_TIMEOUT=xxx`, xxx being minutes.

Cheers
