### ISSUE TITLE
[BUG] Missing documentation about the alert_severity_id

### ISSUE THREAD

**Issue by CyberAbwehr** [dfir-iris/iris-web#298]
**Describe the bug**
I test all alert_severity_id in IRIS, because it is imported to know
what alert severity i need to send from other applications like wazuh, suricata, opensearch, aso.

alert_severity_id = 1 (Unspecified)
alert_severity_id = 2 (Informational)
alert_severity_id = 3 (Low)
alert_severity_id = 4 (Medium)
alert_severity_id = 5 (High)
alert_severity_id = 6 (Critical)

Please can you add this to the documentation.

**Expected behavior**
Need to be in the documentation

**Comment by tboy-hacker** [comment]
Wazhu -> Shuffle -> DFIR-IRIS (2.3.2) pls have did you get this to work and drop the shuffle link for iris

**Comment by lnn2204** [comment]
I saw it somewhere and thought it was in the docs, just in case you need alert_status_id:

1 - Unspecified
2 - New
3 - Assigned
4 - In progress
5 - Pending
6 - Closed
7 - Merged

**Comment by whikernel** [comment]
Hi! 

Indeed we're missing some endpoints in the documentation (which aims to be updated, we didn't find the time yet). 
You can use this endpoint to list the alerts_severity_id: https://xxxx/manage/severities/list. 

You can also see the available endpoints with https://xxx/sitemap  

We'll update the documentation!

Cheers

**Comment by tboy-hacker** [comment]
@CyberAbwehr will love to connect

**Comment by CyberAbwehr** [comment]
@tboy-hacker post your email address, so we can connect.

best regard

**Comment by tboy-hacker** [comment]
@CyberAbwehr brightkids545@gmail.com
