### ISSUE TITLE
[BUG] Percentage symbol on case title breaks manage cases list

### ISSUE THREAD

**Issue by codref** [dfir-iris/iris-web#302]
**Describe the bug**
Should a case contain a percentage "%" symbol/character on the title field, the "manage cases list" at the url `/manage/cases` is not populated. The browser javascript console contains errors.

**To Reproduce**
1. Go to "manage cases"
2. Fill the general info form and put in the *case name* field the value `Something with % on title`
3. Click "create"
4. Go to "manage cases"
5. Click on "cases list"

**Expected behavior**
The list should contain the list of cases in the system.

**Screenshots**
![image](https://github.com/dfir-iris/iris-web/assets/1255315/540a0ddc-d3b8-4a6a-93e3-b2892fe129ae)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox 115.0.2, Chrome 116.0.5845.140

**Additional context**
Javascript console reports below stack trace:  

```
manage.cases.js:139 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at render (manage.cases.js:139:92)
    at datatables.min.js:17:6970
    at n.fnGetData (datatables.min.js:17:3728)
    at _ (datatables.min.js:17:6174)
    at P (datatables.min.js:17:10069)
    at D (datatables.min.js:17:5951)
    at datatables.min.js:17:22328
    at u (datatables.min.js:17:15463)
    at Object.success (datatables.min.js:17:15670)
```

**Comment by whikernel** [comment]
Hi @codref 

Indeed, thanks a lot. We'll fix this in the next patch 👍 

Cheers
