### ISSUE TITLE
[BUG] Python requirements.txt failure since new major version of Werkzeug

### ISSUE THREAD

**Issue by em-am** [dfir-iris/iris-web#314]
**Describe the bug**
It looks like a major update (3.0.0) of the Werkzeug module published the 30th September has broken flask_login who uses a specific import of Werkzeug that has been deprecated by this update.
See "urls" submodule for 3.0.0 : https://werkzeug.palletsprojects.com/en/3.0.x/urls/
Compared to the 2.x branch : https://werkzeug.palletsprojects.com/en/2.3.x/urls/

Workers exits at start : 
```
iriswebapp_app       | Running iriswebapp ...
iriswebapp_app       | [2023-10-02 13:28:52 +0000] [7] [INFO] Starting gunicorn 20.1.0
iriswebapp_app       | [2023-10-02 13:28:52 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
iriswebapp_app       | [2023-10-02 13:28:52 +0000] [7] [INFO] Using worker: eventlet
iriswebapp_app       | [2023-10-02 13:28:52 +0000] [9] [INFO] Booting worker with pid: 9
iriswebapp_app       | [2023-10-02 13:28:52 +0000] [9] [ERROR] Exception in worker process
iriswebapp_app       | Traceback (most recent call last):
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
iriswebapp_app       |     worker.init_process()
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 134, in init_process
iriswebapp_app       |     super().init_process()
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
iriswebapp_app       |     self.load_wsgi()
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
iriswebapp_app       |     self.wsgi = self.app.wsgi()
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
iriswebapp_app       |     self.callable = self.load()
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
iriswebapp_app       |     return self.load_wsgiapp()
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
iriswebapp_app       |     return util.import_app(self.app_uri)
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
iriswebapp_app       |     mod = importlib.import_module(module)
iriswebapp_app       |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
iriswebapp_app       |     return _bootstrap._gcd_import(name[level:], package, level)
iriswebapp_app       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
iriswebapp_app       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
iriswebapp_app       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
iriswebapp_app       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
iriswebapp_app       |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
iriswebapp_app       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
iriswebapp_app       |   File "/iriswebapp/app/__init__.py", line 29, in <module>
iriswebapp_app       |     from flask_login import LoginManager
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/flask_login/__init__.py", line 12, in <module>
iriswebapp_app       |     from .login_manager import LoginManager
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/flask_login/login_manager.py", line 33, in <module>
iriswebapp_app       |     from .utils import _create_identifier
iriswebapp_app       |   File "/opt/venv/lib/python3.9/site-packages/flask_login/utils.py", line 14, in <module>
iriswebapp_app       |     from werkzeug.urls import url_decode
iriswebapp_app       | ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/opt/venv/lib/python3.9/site-packages/werkzeug/urls.py)
iriswebapp_app       | [2023-10-02 13:28:52 +0000] [9] [INFO] Worker exiting (pid: 9)
iriswebapp_app       | [2023-10-02 13:28:52 +0000] [7] [INFO] Shutting down: Master
iriswebapp_app       | [2023-10-02 13:28:52 +0000] [7] [INFO] Reason: Worker failed to boot.
```

**To Reproduce**
Build image with `docker build --network=host -t iriswebapp_app:v2.3.2 -f docker/webApp/Dockerfile .`
Run with docker-compose

**Expected behavior**
Werkzeug dependency rule in requirements.txt should set the last version of the 2.x branch "Werkzeug==2.3.7" instead of "Werkzeug>=2.2.3" to allow flask-login to use the fonction url_decode while waiting for the flask-login update recently added on https://github.com/maxcountryman/flask-login/commit/7b170bf4e5e0240fe084166c9ca6ec4fba258dcd

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Docker 24.0.5 (rootless variant)

**Additional context**

**Comment by chromefinch** [comment]
yep, how do I fix this?
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/opt/venv/lib/python3.9/site-packages/werkzeug/urls.py)

**Comment by lukemilby** [comment]
> yep, how do I fix this? ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/opt/venv/lib/python3.9/site-packages/werkzeug/urls.py) I've updated source/requirements.txt to "Werkzeug==2.3.7"

Having the same issue

**Comment by aj-tap** [comment]
As a temporary solution, Before building the Docker image, I made a temporary fix by editing the dependency in the source/requirements.txt file as follows:

Flask==2.2.2
Werkzeug==2.2.3

**Comment by chromefinch** [comment]
Thank you! 
But I'm still getting the same error. 
No joy

**Comment by whikernel** [comment]
Hi! 
Thanks for raising that! Indeed fixing the version `Werkzeug==2.3.7` is working on our side. 
@chromefinch - can you please do it again by forcing to clear the cache? `docker compose build --no-cache`  

We'll push the fix asap.

**Comment by chromefinch** [comment]
> Hey, i tried to build the containers one time with
> 
> Flask==2.2.2 Werkzeug==2.2.3
> 
> and another time with
> 
> Werkzeug==2.3.7
> 
> neither of them worked for me. I still recieve the message IRISwebapp is unavailable - sleeping

Did you rebuild?

docker compose build --no-cache

**Comment by whikernel** [comment]
Hi @JN778!

Can you please check the upper logs to see why the webapp is not starting? It may not be related to this issue then

**Comment by lukemilby** [comment]
> Hi! Thanks for raising that! Indeed fixing the version `Werkzeug==2.3.7` is working on our side. @chromefinch - can you please do it again by forcing to clear the cache? `docker compose build --no-cache`
> 
> We'll push the fix asap.

This worked thank you! 

updated `Werkzeug==2.3.7` in. `/iris-web/source/requirements.txt`
`docker compose down --volumes`
`docker compose build --no-cache`
