### ISSUE TITLE
[BUG] Error after installation unable to access the web panel

### ISSUE THREAD

**Issue by JN778** [dfir-iris/iris-web#315]
Hello there, 

i run over the following bug during installation:

**Describe the bug**
After following the default installation and starting the containers with docker-compose up the following error appears:
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_nginx     | 2023/10/04 19:45:30 [error] 10#10: *69 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: iris.app.dev, request: "GET / HTTP/1.1", upstream: "http://172.18.0.2:8000/", host: "127.0.0.1"
iriswebapp_nginx     | 127.0.0.1 - - [04/Oct/2023:19:45:30 +0000] "GET / HTTP/1.1" 502 497 "-" "curl/7.64.0" "-"
iriswebapp_nginx     | 2023/10/04 19:45:30 [info] 10#10: *69 client 127.0.0.1 closed keepalive connection
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_worker    | IRISwebapp is unavailable - sleeping

In the Browser under port 443 i recieve 
An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

Tried to install it under Ubuntu 22.04 and Debian 12 both with the same error. Even in completly newvms build in under Virtualbox

**To Reproduce**
Create a new VM with Debain12 or Ubuntu 22.04 VM in Virtualbox
Follow the installation
#  Clone the iris-web repository
git clone https://github.com/dfir-iris/iris-web.git
cd iris-web

# Checkout to the last tagged version 
git checkout v2.3.2

# Copy the environment file 
cp .env.model .env

# Build the dockers
docker-compose build

# Run IRIS 
docker-compose up

-> Recieve the error i mentioned under **Describe the bug** after running -> docker-compose up

**Expected behavior**
The webinterface should start normaly

**Desktop (please complete the following information):**
 - Installed under virtuelbox 7.0.10 in a completly new ubuntu 22.04 and debian12 vm
 - Browser -> Tried to access the web panel over edge and firefox

**Comment by TPower2112** [comment]
We ran into this exact issue yesterday. We will check #314

**Comment by mickitcarlow** [comment]
Having the same issue. Tried multiple VMs and directly on host hardware. Ubuntu 20.04.

**Comment by whikernel** [comment]
Hi @JN778, @mickitcarlow, 

Can you show us the error logs when the app is starting please? We installed multiple times on Ubuntu and got no issues so far.

**Comment by AnarulHossain** [comment]
I faced the similar kind of problem. Trying different processes but none working for me , finally i found a silly solution. First completely uninstall docker and iris associate file from system. Then reinstall docker. Before install iris (docker-compose build) while change .env file keep in mind the key and password will be without special character & not too long . It seems very silly but worked for me . Hopefully your problem will be solved.
