### ISSUE TITLE
[BUG] sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "@db" to address: Name or service not known

### ISSUE THREAD

**Issue by 0c34** [dfir-iris/iris-web#322]
**Describe the bug**
Hi i encounter this error when starting the docker compose
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "@db" to address: Name or service not known

**Comment by swerver-t** [comment]
was this issue ever corrected? If so what was the fix... I am able to reproduce this error after a couple days of Iris worker being up
