### ISSUE TITLE
Export timeline as JPEG/PNG

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#33]
Export the timeline as JPEG/PNG or foresee the option to include it in a report.
(maybe something similar as the MISP Relations tab where you can export the 'view'? [https://www.misp-project.org/assets/images/misp/blog/anothergraph.png](https://www.misp-project.org/assets/images/misp/blog/anothergraph.png))

**Comment by whikernel** [comment]
Added in https://github.com/dfir-iris/iris-web/tree/i33_export_aspng  
New button on quick right pane to take a screen shot of the content of the inner page.  
Some content might not render properly depending on the situation. Work for all case pages except summary.  

![image](https://user-images.githubusercontent.com/74464599/148353029-ee67d21d-f054-434e-83e1-c0b12c31c5b9.png)
