### ISSUE TITLE
[FR] Configuration for session Timeout

### ISSUE THREAD

**Issue by wonhee0410** [dfir-iris/iris-web#338]
Hi all,

My company regulation has a section of session timeout, it requires that user must be automatically logout after 15 minutes inactivity.

Could you please add a feature that can configure the session timeout or another way to do that, thanks you.

**Comment by m-terlinde** [comment]
We have this regulation as well, but I went with "non compliance" so far :D

**Comment by whikernel** [comment]
Hi, 

It is now possible by setting `IRIS_SESSION_TIMEOUT=xx`, with xx being minutes. 

Cheers

**Comment by m-terlinde** [comment]
Thanks a lot!
