### ISSUE TITLE
[BUG] Case filtering sorting issue

### ISSUE THREAD

**Issue by Acsigen** [dfir-iris/iris-web#345]
**Describe the bug**
When clicking on the textbox to filter the cases inside `Manage cases` menu, the cases are sorted.

**To Reproduce**
1. Go to 'Manage cases'
2. Click on 'Any textfield to filter the data'
4. The case list is getting sorted by that field

**Expected behavior**
This should happen only when the sort button is pressed.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 119.0.6045.200

**Additional context**
Iris Version: 2.3.5

**Comment by Ektoplasma** [comment]
Issue related to DataTables js plugin
