### ISSUE TITLE
[FR] API - Filter cases

### ISSUE THREAD

**Issue by barn4k** [dfir-iris/iris-web#352]
**Is your feature request related to a problem? Please describe.**
There is no option to filter cases within API.

**Describe the solution you'd like**
I suppose the endpoint **/manage/cases/list** should act the same as **/alerts/filter**

**Describe alternatives you've considered**
For now the only option is to filter alerts and get the relevant **cid** from them

**Additional context**
For example if I have even 10k of cases, I cannot get all of them due to the very excessive output (I usually use AWS Lambda that has a limitation of 2MB for the output payload). And as I can't select desired fields, it's quite impossible to avoid memory error or payload limitation.

Main reason for that functionality: to develop a playbook/process where I need to create an incident with some evidences and later populate that case with additional evidences, comments and update tasks.

**Comment by whikernel** [comment]
Hi @barn4k  

There is actually an endpoint which isn't documented yet. 
By reaching `/manage/cases/filter` you will be able to filter the cases and get a pagination.  

It expects a GET request with optionally the following filters as parameters.  

- `case_ids`- Comma separated list of IDs
- `case_customer_id`
- `case_name`
- `case_name`
- `case_description`
- `case_classification_id`
- `case_owner_id`
- `case_opening_user_id`
- `case_severity_id`
- `case_state_id`
- `case_soc_id`
- `start_open_date`
- `end_open_date`
- `sort` (desc or asc) 
- `page` - page number 
- `per_page` - number of results returned 

Let me know if it fits what you are looking for. 
Cheers

**Comment by barn4k** [comment]
hi @whikernel 

oh, great. That is what I'm looking for. Thanks.

**Comment by barn4k** [comment]
@whikernel 

Interesting, but the endpoint return results in the wrong parameter (message instead of data)
<img width="440" alt="image" src="https://github.com/dfir-iris/iris-web/assets/15629670/35a96796-32dd-48c1-9969-5b027aa774a7">
