### ISSUE TITLE
Hooks on object creations / updates

### ISSUE THREAD

**Issue by whikernel** [dfir-iris/iris-web#36]
Create the possiblity to add hooks upon creation or updates of case objects. For example, this would allow to  : 

- Automatically enhance an IOC with third-party sources (VT, MISP, etc) 
- Automatically push an object (IOC, assets, event, notes, etc) to a third party platform 
- And much more

**Comment by admSpiker** [comment]
Добрый день. В некоторой степени присоединяюсь к просьбе. Предполагается ли возможность получения web-hooks в формате json для интеграции с проектом Hive. Если вас заинтересует я мог бы предоставить пример Json.

**Comment by whikernel** [comment]
Hi @admSpiker  

Hooks we will most likely be under the form of generic modules that can reacts on events such as `creation`, `updates` and `deletion` of case objects. This mean a module, with the data in hand after being notified, will be able to request anything it wants in the format it wants. So a Cortex module will simply register to these hooks,  push the data to Cortex in the correct form, wait for the data and then update IRIS as needed.
