### ISSUE TITLE
[FR] Add screenshot to timeline event descriptions, asset and IOC descriptions

### ISSUE THREAD

**Issue by CyberSpooon** [dfir-iris/iris-web#375]
**Is your feature request related to a problem? Please describe.**
Similar to the functionality implemented in issue #30, it would be great to add screenshots from the clipboard to timeline event descriptions. This would, a) potentially reduce time spent on creating and typing out descriptions for individual events and b) allow analysts to provide more context to existing event descriptions since screenshots can be excellent forms of supplementary evidence. While this specific issue highlights the need to add screenshots to event timeline descriptions specifically, it would be extremely helpful to be able to include screenshots from the clipboard in all description fields across the entire DFIR IRIS platform.

**Describe the solution you'd like**
Ability to upload screenshots from clipboard or from disk in to the timeline event description, asset description, and IOC description. It would also be helpful to upload a screenshot/picture saved on disk as a single evidence item in the evidence tab.

**Comment by whikernel** [comment]
Hi @CyberSpooon - 

All description fields of the case objects are MD enabled and can thus render images. These images might need to be uploaded to the datastore first if the copy/paste isn't working. You need to click on the `eye` icon on the description fields to render the MD. This is mostly due to the lack of space in the modals. 
We're open to any suggestions to make this better 👍 

![image](https://github.com/dfir-iris/iris-web/assets/74464599/379e7a78-85e1-44c8-9339-933a5092337d)

![image](https://github.com/dfir-iris/iris-web/assets/74464599/fdefc51e-74c0-4f02-8f25-bb1e15defe2e)

**Comment by CyberSpooon** [comment]
Hi @whikernel,

Thanks for the quick reply! I did notice that I could add screenshots by first uploading them to the datastore and entering the MD into the desired description. However, I am hoping for a more seamless way to enter screenshots by simply copy/pasting them from the clipboard to the IOC, asset, or timeline description fields. That is how it works in the case summary field which is fantastic! Hoping to see that same screenshot copy/paste functionality in the case summary field also built into other description fields on the platform (see screenshot below). Hope that clarifies things!

![DFIR-IRIS Screenshot](https://github.com/dfir-iris/iris-web/assets/137320651/e7967fa4-5f9a-43f7-add0-ed0228603701)
Screenshot copy/paste functionality to potentially be implemented across all description fields in IRIS.

Thanks!

**Comment by YouBaxter** [comment]
100% on this!  
in the timeline, pasting images/snippits would be a HUGE benefit.  Simply for context adds and not necessarily IOCs.

**Comment by elsid2020** [comment]
I'd like to add my support for this enhancement. The image paste functionality in the case summary editor works perfectly. Extending this to the other description fields (Timeline, IOC, assets, etc) would be a great benefit.

**Comment by whikernel** [comment]
It is now the case since a few versions 👍

**Comment by YouBaxter** [comment]
Apologies; but is this completed?  Totally get it that you can link to the datastore but I think what req'd is the copy/paste function into the text block itself.  
Or, are we saying at the current state (without a bigger app rebuild); this isn't possible.


Example; I want to open a case, paste a picture in the "timeline"

Thanks!!!
