### ISSUE TITLE
How to develop on-the-fly﻿ and with breakpoint into PyCharm?

### ISSUE THREAD

**Issue by BorderCloud** [dfir-iris/iris-web#39]
I'm a newbie with gnuicorn.

Can you add a configuration where it's possible to develop this project on-the-fly﻿ and with breakpoint into PyCharm ? Or a documentation/video ?

Thanks

**Comment by whikernel** [comment]
Hi @BorderCloud 

We don't have a development documentation yet but it will come at some point. In the meantime - as you wrote - we recommend using a hybrid development environment, as most of the time only the web-app needs to be changed: 

- Pycharm for the web-app 
- Docker for db, nginx, celery and worker. The three laters are even optional if you don't develop modules. 

## Web-app 
For the webapp configuration, you only need to create a `config.priv.ini` in source/app by copying the `config.docker.ini`present in the same directory. Then change `PG_SERVER = db` to  `PG_SERVER = 127.0.0.1`.  
That's the only configuration change you will need for the app to run outside docker. The `docker.priv.ini` is already excluded in gitignore. 

You then need to setup Pycharm with a dedicated environment by adding a new configuration:
- Script path : `source/run.py`
- Python interpreter 3.8 
- Working directory: `source`

To have pylint, right click on `source` in the directory tree and `mark directory as` > `sources root`. 
You also need to install the requirements - all in requirements.txt - in the new environment, either with Pycharm or the CLI. 

## Run 
1. Spin up the docker db `docker compose up db`
2. Run the Pycharm configuration you created 
3. The interface should be accessible on http://127.0.0.1:8000 (and https://127.0.0.1:4433 if you started the nginx docker) 

You can now develop and debug on the fly. 

## Tests in docker 
Once your code is working by running on Pycharm, we highly recommend to test it on Docker. To do so, you need to erase and rebuild the app docker entirely - rebuilding only might not work depending on your changes.    

1. `docker compose rm app`
2. `docker compose build app`
3. `docker compose up db app`

**Development considerations**   
If your development results in DB modification, please use Alembic and add a migration script so users don't loose their data when they upgrade.

**Comment by whikernel** [comment]
Fixed in https://github.com/dfir-iris/iris-doc-src/commit/655e9556a51d3bcdf824f9be5f32fb34abd39b85#diff-f332ef2fad4f40a95f388dda9aa1a66e0b121d95b36aa7fc7261318be34a0e41
