### ISSUE TITLE
[BUG] - Wazuh Alerts does not shows in Alert Pages

### ISSUE THREAD

**Issue by KhaledEid020** [dfir-iris/iris-web#392]
Wazuh Alerts does not show in Alert Pages but it shows in activity tap.

![0alerts](https://github.com/dfir-iris/iris-web/assets/46486159/d91f8704-2090-4592-9d0a-9f394261d863)

![alerts](https://github.com/dfir-iris/iris-web/assets/46486159/a14c1b70-b883-42e5-bd5f-ba37ea70d4bd)

Wazuh ossec.conf:
![xcalerts](https://github.com/dfir-iris/iris-web/assets/46486159/2edb5261-c948-4133-ad4a-d17a8dfc1c37)

 - Ubuntu 22
 - Try it in all browsers and still the same error.
 
 Any help will be great.

**Comment by whikernel** [comment]
HI @KhaledEid020 

Which version of IRIS are you using? 
If you upgraded to v2.4.5, there's been a change in the access control and it's normal that alerts are not shown by default. 
The documentation is on its way but it's taking some time. 

If you are on v2.4.5 please let me know so I'll explain how to add the proper rights. 

Cheers

**Comment by whikernel** [comment]
Hi @melman-git 
Could you please check that your user is linked to the corresponding customers? 

https://docs.dfir-iris.org/2.4.5/operations/upgrades/#v240

You need to go to access control > Users > Your User > Customers and add yourself. 

Let me know if it works

**Comment by KhaledEid020** [comment]
It works when I run them on different servers.

Appreciate your answer!
