### ISSUE TITLE
Changing Admin Password Question

### ISSUE THREAD

**Issue by denizciftci-sec** [dfir-iris/iris-web#393]
Hi Team,

I am trying to change the admin password of the IRIS.
I was able to generate the bcrypt hash as

(example)

print(bcrypt.hashpw('<test123!>'.encode('utf-8'), bcrypt.gensalt()))
b'$2b$12$0dw1nDVrxkYkexByJDv6r.nH.byUMN6OZg0.gcsMMpDM0N6SRewLO'

Is this the correct format when adding the hash in iris db container? I am still not able to change the administrator password successfully?

UPDATE "user" SET password = '<$2b$12$0dw1nDVrxkYkexByJDv6r.nH.byUMN6OZg0.gcsMMpDM0N6SRewLO>' WHERE "user".name
UPDATE 1

**Comment by whikernel** [comment]
Hi @denizciftci-sec 

You need to remove the <> around your hash. This is an indication of where the hashed pwd should be replace.

Cheers
