### ISSUE TITLE
[BUG] Module installation 

### ISSUE THREAD

**Issue by KhaledEid020** [dfir-iris/iris-web#397]
When I run the script you provide in the module documentation, i get these errors

I was trying to integrate the cortex.

How i can solve it?
![IMG-20240201-WA0001](https://github.com/dfir-iris/iris-web/assets/46486159/477097de-046c-4266-b67e-b63ca7d582e8)
![IMG-20240201-WA0000](https://github.com/dfir-iris/iris-web/assets/46486159/23aa1dd9-2b49-4ce4-98d6-2829fdc293dc)

**Comment by Noones47** [comment]
How did you manage to solve this issue?
