### ISSUE TITLE
docker-compose build: make: pg_config: Operation not permitted

### ISSUE THREAD

**Issue by k4rmap** [dfir-iris/iris-web#40]
Hi, 
im having the follow issue when i try to build the db:

Building db
Sending build context to Docker daemon  4.096kB
Step 1/5 : FROM postgres:12-alpine
 ---> 71f18539f112
Step 2/5 : RUN apk add --update --no-cache clang clang-dev llvm
 ---> Using cache
 ---> 1fad64366555
Step 3/5 : RUN apk add --update --no-cache clang-extra-tools
 ---> Using cache
 ---> 2f5aeee954fd
Step 4/5 : RUN apk add --update --no-cache git build-base  && git clone https://github.com/eulerto/pg_similarity.git  && cd pg_similarity  && USE_PGXS=1 make  && USE_PGXS=1 make install  && apk del git build-base  && rm -rf /var/cache/apk/*
 ---> Running in 4165589e2fc2
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/25) Installing binutils (2.37-r3)
(2/25) Installing libmagic (5.41-r0)
(3/25) Installing file (5.41-r0)
(4/25) Installing libgomp (10.3.1_git20211027-r0)
(5/25) Installing libatomic (10.3.1_git20211027-r0)
(6/25) Installing libgphobos (10.3.1_git20211027-r0)
(7/25) Installing gmp (6.2.1-r0)
(8/25) Installing isl22 (0.22-r0)
(9/25) Installing mpfr4 (4.1.0-r0)
(10/25) Installing mpc1 (1.2.1-r0)
(11/25) Installing gcc (10.3.1_git20211027-r0)
(12/25) Installing musl-dev (1.2.2-r7)
(13/25) Installing libc-dev (0.7.2-r3)
(14/25) Installing g++ (10.3.1_git20211027-r0)
(15/25) Installing make (4.3-r0)
(16/25) Installing fortify-headers (1.1-r1)
(17/25) Installing patch (2.7.6-r7)
(18/25) Installing build-base (0.5-r2)
(19/25) Installing ca-certificates (20191127-r7)
(20/25) Installing brotli-libs (1.0.9-r5)
(21/25) Installing nghttp2-libs (1.46.0-r0)
(22/25) Installing libcurl (7.80.0-r0)
(23/25) Installing expat (2.4.1-r0)
(24/25) Installing pcre2 (10.39-r0)
(25/25) Installing git (2.34.1-r0)
Executing busybox-1.34.1-r3.trigger
Executing ca-certificates-20191127-r7.trigger
OK: 560 MiB in 71 packages
Cloning into 'pg_similarity'...
make: pg_config: Operation not permitted
make: *** No targets.  Stop.
The command '/bin/sh -c apk add --update --no-cache git build-base  && git clone https://github.com/eulerto/pg_similarity.git  && cd pg_similarity  && USE_PGXS=1 make  && USE_PGXS=1 make install  && apk del git build-base  && rm -rf /var/cache/apk/*' returned a non-zero code: 2
ERROR: Service 'db' failed to build : Build failed

Thanks!

**Comment by whikernel** [comment]
Hi @k4rmap 

Could you please tell us more about your environment (Windows, Windows with WSL, Linux, Mac, docker versions, etc)?

Thanks !

**Comment by admSpiker** [comment]
I have the same problem.

**Comment by whikernel** [comment]
Hey @k4rmap , 

Could you please also tell us more about your environment ? 
Thanks

**Comment by whikernel** [comment]
@admSpiker  Are you running SELinux by any chance ?

**Comment by admSpiker** [comment]
SELinux status: disabled.
Assembly according to the instructions causes a similar error. We made a build based on postgres:alpine3.13 no error occurred.
