### ISSUE TITLE
Auto saving notes [FR]

### ISSUE THREAD

**Issue by k05h250** [dfir-iris/iris-web#441]
Feature: Auto saving notes
Since switching to the new edito for notes we are seeing that the notes no longer auto save and is causing some issues with information disappearing if an anaylist doesn't click save, granted this is partly a workflow issue.

Solution:
If the feature to auto save the note when information has been added or the user be prompted to save the information in the note if they user clicks away from the current note with changes, that would be greatky appreciated.

DFIR IRIS Version : v2.4.5

**Comment by whikernel** [comment]
Hey! 

This has been reimplemented in IRIS v2.4.7 :)
