### ISSUE TITLE
[BUG] Alert "Close with note" throws: {'alert_classification_id': ['Not a valid integer.']}

### ISSUE THREAD

**Issue by tientmse62290** [dfir-iris/iris-web#467]
**Describe the bug**
Sorry if my question is silly.
When I receive an alert, with the provided information I can be sure that the alert is FP. Then I click on "close with note" and fill like the picture, but they throw an error popup: {'alert_classification_id': ['Not a valid integer.']}

![image](https://github.com/dfir-iris/iris-web/assets/28757980/165bf4bb-41ef-4b07-92ed-02d0629e6ac7)
I cannot close with note, just able to click on "close" only button.

Source alert: elastalert2 with default config, only change the customer id
I upgraded from 2.3.7 to 2.4.7 but it till throws this error.
Anyone suffer that?
Thx

**Comment by whikernel** [comment]
Hi! 

Thanks for reporting. It's because the alert was created without a classification ID. I just fixed the update without having to provide one 👍
