### ISSUE TITLE
[BUG] Multiple investigation report template issues

### ISSUE THREAD

**Issue by KALRONG** [dfir-iris/iris-web#478]
**Describe the bug**
While trying to generate a new template for reporting I have found a couple of issues: 

- Report language always shows as french in the drop down menu for template selection on the case
- case.for_customer tag not working, using case.client.customer_name works

**To Reproduce**
1. Generate a docx template with "{{ case.for_customer }}" tag inside
2. Save it and upload it to IRIS and select any language different other than french.
3. Got to generate report on the case dashboard and select the report template (here the language will always show as french)
4. Generate report, the tag will be empty and no error or None reported

**Expected behavior**
- Display the corrent language when selecting the template
- Tag should work as expecified on the documentation

**Desktop (please complete the following information):**
 - OS: IRIS running under Debian Bookworm, client running Windows 11
 - Browser: Chrome and Firefox
 - Version: 2.4.7

**Comment by Vladimir-A** [comment]
Fixed in #632
