### ISSUE TITLE
[Request] Additional ways to log in

### ISSUE THREAD

**Issue by pixelnull** [dfir-iris/iris-web#49]
This is just a request for TODO, OAUTH2 and LDAP would be nice features in the future.

Thanks and look forward to this project in the future.

**Comment by whikernel** [comment]
Hi @pixelnull,

This is actually already in progress! We don't have any ETA on that, but it will implemented in a future release for sure.

**Comment by spliggity** [comment]
Would you be open to considering SAML authentication as a possible enhancement?  I'd be happy to work on it if others see value.  Thanks and sorry if I'm commenting in the wrong spot!

**Comment by maikroservice** [comment]
@spliggity are you still up for it? I am working on saml integration right now
