### ISSUE TITLE
[BUG] Alerts are not shown in the GUI

### ISSUE THREAD

**Issue by migr19** [dfir-iris/iris-web#490]
After importing an Alert via API or with python client the alerts are not shown in the GUI.
When i merge via Python Client an alert to a case, it shows 1 related alert, but after clicking on it, get redirected to the empty Alert page.
alert_get via Python Client works. 

IRIS server version: v2.4.7
Database revision: 35c095f8be2b
Min. API version supported: 2.0.4
Max. API version supported: 2.0.5
Min. module interface version supported: 1.1
Max. module interface version supported: 1.2.0

![image](https://github.com/dfir-iris/iris-web/assets/172152160/1d073ba6-b266-46d6-80c9-edfc61e96474)
![image](https://github.com/dfir-iris/iris-web/assets/172152160/bcae4fdc-da59-4823-ba45-13e120a2bdbd)
![image](https://github.com/dfir-iris/iris-web/assets/172152160/91399cd4-5a0e-4459-89df-56eab1f9f4c8)
![image](https://github.com/dfir-iris/iris-web/assets/172152160/703901c9-da56-4e2d-8a69-a2949fc275c0)

Response from API alerts/add
{"status": "success", "message": "", "data": {"severity": {"severity_id": 3, "severity_name": "Informational", "severity_description": "Informational"}, "status": {"status_id": 2, "status_name": "New", "status_description": "Alert is new and unassigned"}, "customer": {"customer_name": "IrisInitialClient", "customer_description": null, "customer_sla": null, "customer_id": 1, "client_uuid": "e3a11340-5657-402a-af5b-ac1bba754124", "creation_date": "2024-06-08T20:44:50.442149", "last_update_date": "2024-06-08T20:44:50.442149", "custom_attributes": null}, "classification": {"name": "abusive-content:spam", "name_expanded": "Abusive-Content: spam", "description": "Spam or \u2018unsolicited bulk e-mail\u2019, meaning that the recipient has not granted verifiable permission for the message to be sent and that the message is sent as part of a larger collection of messages, all having identical content.", "id": 1, "creation_date": "2024-06-08T20:44:49.309196"}, "owner": null, "iocs": [{"ioc_value": "hostname1", "ioc_enrichment": null, "ioc_type": {"type_name": "hostname", "type_description": "A full host/dnsname of an attacker", "type_taxonomy": null, "type_validation_regex": null, "type_validation_expect": null, "type_id": 69}, "ioc_id": 19, "ioc_uuid": "73752d79-f5ed-462a-ac3c-546c46f7fd46", "ioc_type_id": 69, "ioc_description": "Hostname", "ioc_tags": "splunk", "user_id": null, "ioc_misp": null, "ioc_tlp_id": 2, "custom_attributes": null, "modification_history": null}, {"ioc_value": "1.1.1.1|443", "ioc_enrichment": null, "ioc_type": {"type_name": "ip-dst|port", "type_description": "IP destination and port number separated by a |", "type_taxonomy": null, "type_validation_regex": null, "type_validation_expect": null, "type_id": 78}, "ioc_id": 20, "ioc_uuid": "ea26251d-253d-4554-b800-95083253e5b8", "ioc_type_id": 78, "ioc_description": "Dest IP and port from Splunk", "ioc_tags": "splunk", "user_id": null, "ioc_misp": null, "ioc_tlp_id": 3, "custom_attributes": null, "modification_history": null}, {"ioc_value": "10.10.10.10", "ioc_enrichment": null, "ioc_type": {"type_name": "ip-src", "type_description": "A source IP address of the attacker", "type_taxonomy": null, "type_validation_regex": null, "type_validation_expect": null, "type_id": 79}, "ioc_id": 21, "ioc_uuid": "b244d9b5-b0c2-447b-8b8a-7b9ac62e4963", "ioc_type_id": 79, "ioc_description": "Source IP from Splunk", "ioc_tags": "splunk", "user_id": null, "ioc_misp": null, "ioc_tlp_id": 2, "custom_attributes": null, "modification_history": null}], "assets": [], "resolution_status": null, "cases": [], "comments": [1, 2], "alert_id": 15, "alert_uuid": "6a593f41-1e3c-4787-9367-98f2407c2fe2", "alert_title": "Sample Alert", "alert_description": "Sample Alert Description", "alert_source": "My source", "alert_source_ref": "sid: splunk.sid", "alert_source_link": "https://splunkcloud.com/search?sid=1234", "alert_source_content": {"splunkData": {"_time": "2024-02-11T18:14:00.000+01:00", "src_nt_host": "hostname1", "src_ip": "10.10.10.10", "dest": "1.1.1.1", "dest_port": "443", "info_min* Connection #0 to host 192.168.211.134 left intact
_time": "1707753600.000", "info_max_time": "1707759613.164", "meta_sid": "3123.1234"}}, "alert_severity_id": 3, "alert_status_id": 2, "alert_context": null, "alert_source_event_time": "2024-02-11T17:14:00", "alert_creation_time": "2024-06-08T22:17:58.181510", "alert_note": null, "alert_tags": "splunk", "alert_owner_id": null, "modification_history": {"1717885078.19118": {"user": "administrator", "user_id": 1, "action": "Alert created"}}, "alert_customer_id": 1, "alert_classification_id": 1, "alert_resolution_status_id": null}}

**Comment by whikernel** [comment]
Hi! 
It's because you need to add your users to the related clients for which you have created the alert: https://docs.dfir-iris.org/latest/operations/upgrades/#v247

**Comment by migr19** [comment]
Thanks missed that ;-)
