### ISSUE TITLE
[BUG] Unable to post to /alerts/add via API

### ISSUE THREAD

**Issue by SysAdminSmith** [dfir-iris/iris-web#504]
Greetings.  I have attempted to configure two different services - LibreNMS & Graylog - to send Alerts to Iris.  Generally, the POST request would be:

POST https://foo.bar.lan/alerts/add  -H 'Authorization: Bearer examplekeyhere' -H 'Content-Type: application/json'

Unfortunately, every attempt is met with a 401 error (both through the respective programs' gui and via the programs' containers cli).

Any suggestion or ideas?

Thank you!

**Comment by whikernel** [comment]
Hi! 
The POST looks ok, it's the way to do it. You can try with cURL or Python and check that it's not an issue with IRIS. 
If it works I would check on the side of LibreN:S and Graylog to see if there's no configuration issue.
