### ISSUE TITLE
[BUG] Cortex Module Integration : [BUILDnPUSH2IRIS] Restarting worker container.. 

### ISSUE THREAD

**Issue by Noones47** [dfir-iris/iris-web#520]
After following the instruction to install and run the building script it gives this Log:
![image](https://github.com/dfir-iris/iris-web/assets/72804294/206b2328-6028-49f0-9552-b0959d12353e)

After that the Iris web app starts giving the error: Iris webapp is sleeping

Then when i prune my docker and relaunch him the module doesnt exist. I followed the tutorials step by step anyone with the same error?

**Comment by Skan24** [comment]
Même problème, y a-t-il une solution ?
