### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by guieusebiogaspar** [dfir-iris/iris-web#521]
**Describe the bug**
When trying to retrieve evidences from the case I get this on the backend:
![backend](https://github.com/dfir-iris/iris-web/assets/59066187/ebcd8fe2-da67-4a40-9a8e-6ca5256c1bcf)

And this on the front-end:

<img width="1170" alt="frontend" src="https://github.com/dfir-iris/iris-web/assets/59066187/1eea6e5f-130f-45a1-aa28-feafd9fffe21">

**To Reproduce**
I don't know how to reproduce it or to work around it.

**Comment by whikernel** [comment]
Hi! 
Can you tell us which version you're using? 
Thanks!

**Comment by guieusebiogaspar** [comment]
I was using 2.4.7.

I figured it out that I had to provide a file_size for this to stop happening.
