### ISSUE TITLE
[BUG] Cortex Module Integration - IRISwebapp is unavailable - sleeping

### ISSUE THREAD

**Issue by Noones47** [dfir-iris/iris-web#525]
**Describe the bug**
After running the buildnpush script the Iris web app starts sleeping and giving a nginx error. I figured out that this only happens after i restart the webapp, if i only restart the worker i can go to the GUI and the Module will be there, but if i either restart the docker or the webapp i will have to prune everything back.

**To Reproduce**
1. Run ./buildnpush2iris.sh in the Cortex Analyzer for IRIS tutorial
2. Check the GUI, will give the NGINX error there

**Expected behavior**
It was supposed to add the module and keep running clear.

**Screenshots**
![image](https://github.com/dfir-iris/iris-web/assets/72804294/95b9047a-9f0a-4880-a5c3-fb8e38e5d1df)

Docker Logs:
![image](https://github.com/dfir-iris/iris-web/assets/72804294/c11135da-85da-4075-af54-579521d457c7)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 2.4.7

**Additional context**
This problem can happen with other modules how are we suppose to add modules if this happens???

**Comment by SaubhagyaDeep** [comment]
I am also facing the same issue... the nginx container goes unhealthy and if I just push the module to the worker ... the GUI opens but still I cant validate the module. 

OS: ubuntu 22.04
Version: 2.4.10

**Comment by Noones47** [comment]
> I am also facing the same issue... the nginx container goes unhealthy and if I just push the module to the worker ... the GUI opens but still I cant validate the module.
> 
> OS: ubuntu 22.04 Version: 2.4.10

Yeah, the pseudo fix that i found is to put the Cortex module in the IRIS build folder and build the IRIS with the module already .

**Comment by whikernel** [comment]
If the worker goes to sleep it means the webApp isn't up. You can check the logs of the webapp to understand why the App crashes. 
I'll close this issue for now, at it is more related to the third party cortex module: https://github.com/socfortress/iris-cortexanalyzer-module

**Comment by Skan24** [comment]
Même problème, y a-t-il une solution ?
