### ISSUE TITLE
[BUG] Issue: Unable to Update Hooks in GUI

### ISSUE THREAD

**Issue by Noones47** [dfir-iris/iris-web#526]
**Describe the bug**
I followed the instructions in the repository to install and configure the iris-cortexanalyzer-module without making any changes. While trying to update module parameters in the DFIR-IRIS GUI, I receive the error message "Unable to update hooks". The nginx container logs show the following:

2024-07-09 15:30:50 192.168.32.1 - - [09/Jul/2024:14:30:50 +0000] "POST /manage/modules/set-parameter/OCMjY29ydGV4YW5hbHl6ZV91cmw=?cid=3 HTTP/1.1" 400 102 "https://localhost/manage/modules?cid=3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"

**Steps Taken**
Cloned the repository.
Ran the buildnpush2iris.sh -a script.
Rebuilt the Docker container.
Attempted to update parameters in the GUI.

**Environment**
OS: Windows
Docker version: 4.24.2
DFIR-IRIS version: 2.4.7

**Comment by whikernel** [comment]
Hi! 

This module is a third-party and not published by us. Something is probably wrong on module side when it registers to the hooks. 
We suggest to open an issue on: https://github.com/socfortress/iris-cortexanalyzer-module  

Cheers
