### ISSUE TITLE
IRIS does not send alerts to Shuffle using Webhook

### ISSUE THREAD

**Issue by FarisThabit** [dfir-iris/iris-web#543]
I am trying to connect IRIS alerts to Shuffle using a Webhook.
The picture below is my Shuffle Workflow, and my Webhoock is in the picture.

![Shuffle Workflow](https://github.com/user-attachments/assets/0f23774a-3d40-48f2-8f9e-46995d107294)

According to IRIS documentation to connect a Webhook, you have to configure the Webhook using JSON format (see the picture below).

![IRIS Webhook Configuration](https://github.com/user-attachments/assets/cc51763d-f2bb-4361-aa16-4db3bc1ceef3)

The picture below shows my Webhook configuration in IRIS.

![Webhoock JSON Configuration](https://github.com/user-attachments/assets/c9daa5df-997c-47ef-8f54-6fbd47e0748c)

After Configuration, No alerts are forwarded to Shuffle despite IRIS receiving alerts from Wazuh (see the picture below).

![IRIS Alerts](https://github.com/user-attachments/assets/6decd06b-e69b-44bc-803f-9ad1758ba2ab)

I need some help in debugging the issue. These pictures show some logs from IRIS and Shuffle respectively.

![IRIS LOGS](https://github.com/user-attachments/assets/a7f8f91e-4135-47ba-a6cd-1dfdc8421478)

![Shuffle Logs](https://github.com/user-attachments/assets/9b4aea2c-a12f-48a4-90fc-a8b58d412647)

**Comment by bvirgilioamnh** [comment]
Hey @FarisThabit  we were able to get it to work with this configuration:
```json
        {
            "name": "Shuffle Webhook - Alert",
            "manual_trigger_name": "Send webhook",
            "active": true,
            "trigger_on": ["on_postload_alert_create", "on_manual_trigger"],
            "request_url": "https://shuffler.example.com/api/v1/hooks/webhook_a21c24e4-15ad-460c-8d92-b2c2dc13ae16",
            "use_rendering": false,
            "request_body": {"alert_data": "${{alerts}}"}
        },
        {
            "name": "Shuffle Webhook - Case",
            "active": true,
            "trigger_on": ["on_postload_case_create"],
            "request_url": "https://shuffler.example.com/api/v1/hooks/webhook_a21c24e4-15ad-460c-8d92-b2c2dc13ae16",
            "use_rendering": false,
            "request_body": {"case_data": "${{cases}}"}
        }
```

However we did run into an issue with Iris's webhook handler converting the alert object to a string instead of dumping it out as JSON. We ultimately decided to write our own webhook handler to skip over a lot of the superfluous templating/rendering.

**Comment by whikernel** [comment]
Hi @bvirgilioamnh 

Iris webhook doesn't wrap it in a string, it should dump the json directly and we're actually using it like this. 
So you should just do 
"alerts":"alerts". 

Also starting from Iris v2.4.12 you can use any specific fields within the object. Something like "case_title": "case.name" will indeed return the string only

**Comment by bvirgilioamnh** [comment]
We'll give that a shot!

**Comment by bvirgilioamnh** [comment]
Looks like that works! Awesome!

**Comment by whikernel** [comment]
Great! 
You can also use strings formatting directly like "alert_title":"the alert title is ${{alerts.alert_title}} and the description is ${{alerts.alert_description}}" 

We'll update the documentation to reflect these new changes.
