### ISSUE TITLE
resolved: [BUG] alerts created via API do not appear in gui - v.2.4.7

### ISSUE THREAD

**Issue by dsek** [dfir-iris/iris-web#547]
Hello,

**Describe the bug**
Alerts which have been successfully added via API do not appear in the gui.

**To Reproduce**
Use any rest api client to add an alert (I'm using curl). Curl Response: alert successfully added with id 1 or 2 or 3 ... or 7 ...
The alerts are added to the system as they appear in the database as well as the iriswebapp_app logs show that the alert was added. 

DB screenshot:
![image](https://github.com/user-attachments/assets/9b44f6f6-2b8b-48b6-bb1a-a424a7bead52)

LOG screenshot:
![image](https://github.com/user-attachments/assets/a086b269-8347-4181-afc7-f3bcefa07c24)

LOG activities:
The system reports that alerts have been added.
![image](https://github.com/user-attachments/assets/c5b0c877-87fe-49c3-b42e-60f1ff6a4d9e)

GUI screenshot:
Counter bubble increases, but no alerts appear in the result list.
![image](https://github.com/user-attachments/assets/1d3088ff-331a-4af6-8653-3e3d815c738d)

**Expected behavior**
Show alerts under section "Alerts" in the gui.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 127.0.1

**IRIS Version**
![image](https://github.com/user-attachments/assets/5fb115ec-5cba-4db6-a62b-ae0093cdd280)

Any ideas what is going one here?

Thx and bye,
dsek

**Comment by migr19** [comment]
You need to add user to the customer - https://github.com/dfir-iris/iris-web/issues/490

**Comment by dsek** [comment]
> You need to add user to the customer - #490

grrr ... i missed that because i missed to "RTFM" ...

https://docs.dfir-iris.org/latest/operations/upgrades/#v247

![image](https://github.com/user-attachments/assets/53b0d992-3977-42a1-a92f-7da536c8c38b)

sorry the circumstances ... and thx to migr19 for the quick response!
