### ISSUE TITLE
[FR] Differentiate in task logs between activities via UI and API

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#55]
**Describe the solution you'd like**
Have a flag in the overview task logs that **differentiates between actions done via the web user interface and via the API**.
Maybe the "user input" column is supposed to cover this? But in the latest version this is always set to false, regardless of actions via UI or API.

**Comment by whikernel** [comment]
The user input is actually set when a task log is added. The message goes in the activity feed and the `user input` is set to true. 
The UI also uses the API, the only difference is the presence of a session cookie. We can probably make the activity tracker get this info. We'll look into it 👍
