### ISSUE TITLE
[FR]Timeline export as png

### ISSUE THREAD

**Issue by migr19** [dfir-iris/iris-web#557]
Great would be if it is able to export the timeline as a png and able to add to report as png.

**Comment by whikernel** [comment]
Hi, 

You can already get a screenshot by going to the top right menu and click Take Screenshot. 

<img width="728" alt="image" src="https://github.com/user-attachments/assets/568957bf-ee41-4aff-bfd8-5af10781a9dc">


<img width="728" alt="image" src="https://github.com/user-attachments/assets/724e528a-e1d0-4ec6-a5fc-6f22d719212c">


For the reporting, it will probably not be implemented as it's quite complex for not that much added value. The timeline image can be pasted afterward in the report. 
Cheers
