### ISSUE TITLE
[BUG] API endpoint for customers is wrong in documentation

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#56]
**Describe the bug**
The API documentation https://dfir-iris.github.io/_static/iris_api_reference.html#operation/post-customer-add refers to the endpoint http://127.0.0.1:8000/customer/add to add customers. This is not correct. 
The correct endpoint is **/manage/customers/add**

**Additional context**
 - Version Iris Build 1.2.1

**Comment by whikernel** [comment]
This endpoint existed in < v1.2.1. We've updated the documentation 👍
