### ISSUE TITLE
[BUG] Docker compose build not working.

### ISSUE THREAD

**Issue by pkmntrainerfrost** [dfir-iris/iris-web#561]
**Describe the bug**
Docker build stops at "[+] Building 0.0s (0/0)".

**To Reproduce**
1. Follow the instructions given on the README

**Screenshots**
![image](https://github.com/user-attachments/assets/7ef2a7b0-abfd-4c4f-a375-802662eb8fa2)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by whikernel** [comment]
Hi! 

Starting from v2.4.8 IRIS is shipped with prebuilt images so it's normal the build step doesn't show anything. 
You can do a docker compose up and the images will be pull from the GCHR repo.

**Comment by pkmntrainerfrost** [comment]
Thanks for the answer! Apologies for my misunderstanding.
