### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by look-a-furry** [dfir-iris/iris-web#567]
**Describe the bug**
Cannot run docker compose. 
ERROR: Cannot extend service 'app' in /home/ubuntu/iris-web/docker-compose.base.yml: services with 'depends_on' cannot be extended

**To Reproduce**
1. Install docker. 
2. Clone the repo
3. Run docker compose
4. ERROR: Cannot extend service 'app' in /home/ubuntu/iris-web/docker-compose.base.yml: services with 'depends_on' cannot be extended

**Expected behavior**
It should compose the container. 

**Screenshots**
![imagen](https://github.com/user-attachments/assets/2727b58a-c6f6-442c-a447-421b608850e9)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: VMware Virtual Platform
 - OS: Ubuntu 24.04 LTS x86_64
 - Browser NONE
 - Version NONE

**Additional context**
Is there a way to run the app without a docker container? I don't use docker containers in my environment, all of my machines are independent VMs running a single program for a specific purpose. I know very well that this is not how you should do this, but this is the way I've been doing it, and I won't change my entire workflow. 

Ive tried different solutions, and all of them point to deleting the depends-on part from the compose file but I guess this is not how it should be done. 

I have absolutely zero experience with docker and I have absolutely zero willingness to learn how to use it. I'd rather run this on real hardware. If this is not possible, please let me know and I will look for a similar program elsewhere.

**Comment by theguly** [comment]
use `docker compose`, not `docker-compose`

**Comment by cbesot** [comment]
same here

**Comment by nativedefenceadmin** [comment]
Same issue..

docker compose version
Docker Compose version 2.24.6+ds1-0ubuntu1~22.04.1

docker --version
Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1

**Comment by nic0echandi** [comment]
I was able to solve it by granting permissions to the user to execute Docker commands.

sudo usermod -aG docker username

then:
$ docker compose pull
[+] Pulling 34/70
[+] Pulling 70/70 - Image is already being pulled by app                       0.0s
 ✔ worker Skipped - Image is already being pulled by app                       0.0s
 ✔ app Pulled                                                                 84.9s
 ✔ nginx Pulled                                                               12.0s
 ✔ rabbitmq Pulled                                                            54.6s
 ✔ db Pulled                                                                  39.5s

and:
docker compose up
