### ISSUE TITLE
[BUG] Spell check not working in various input editors

### ISSUE THREAD

**Issue by lrapp-adan** [dfir-iris/iris-web#570]
**Describe the bug**
The browser's spell check feature is not working in various editors inside iris-web.

**To Reproduce**
1. Go to a case timeline
2. Click on 'Add event'
3. Type misspelled words into the event description
4. Neither the browser internal spell check feature, nor plugins like LanguageTool work inside the editor input area.

**Expected behavior**
Spell check works as it does in common `textarea` input fields.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Mozilla Firefox
 - Version: 129.0

**Comment by whikernel** [comment]
It's now fixed on v2.4.11 and onward

**Comment by lrapp-adan** [comment]
Thanks for the quick fix! :)

I can confirm that I get highlighting of misspelled words in v2.4.12.
However, the right-click context menu of the browser spell checker seems to be broken, but I'm not sure if this is a problem with the browser or with IRIS.

**Describe the bug**
The browser's `Check Spelling` checkbox is unchecked, no context menu with spelling suggestions is shown.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to a case timeline
2. Click on 'Add event'
3. Type misspelled words into the event description
4. Right-click on misspelled word → Enable `Check spelling`
5. Select any other input field
6. Select event description again and type something
7.  `Check spelling` is disabled again and no context menu with spelling suggestions is shown. (but misspelled words are still highlighted)

**Expected behavior**
`Check spelling` checkbox is continuously enabled, context menu with spelling suggestions is shown.

Also, the LanguageTool browser extension does not work, but this seems to be a problem with the extension, which seemingly only works properly with `textarea` or `input` fields.
