### ISSUE TITLE
[BUG] Alerts are not showing in the customer alerts list.

### ISSUE THREAD

**Issue by CyberneticsPlus** [dfir-iris/iris-web#579]
I have integrated the iris with wazuh and wanted to get the alerts to new customer i have created and the ID of the customer is 2. Alerts are getting created but i am not seeing the alerts when i go to Advance - > customer. I am not seeing the alerts both in customer 1 or 2.
 
<img width="1510" alt="Screenshot 2024-09-11 at 2 16 00 PM" src="https://github.com/user-attachments/assets/05d31914-8ec9-474e-ae7c-ff3d21b0b767">
<img width="1500" alt="Screenshot 2024-09-11 at 2 20 13 PM" src="https://github.com/user-attachments/assets/277a0fe2-1462-42c5-ab45-cef05bf15347">
<img width="1512" alt="Screenshot 2024-09-11 at 2 21 23 PM" src="https://github.com/user-attachments/assets/e3dc3af4-37ef-427b-b020-2f7c5b11cf8b">
<img width="1512" alt="Screenshot 2024-09-11 at 2 21 39 PM" src="https://github.com/user-attachments/assets/69cf2fa6-a3c8-4e10-80a6-eecd024e99aa">

**Comment by whikernel** [comment]
Hello! 

The alerts are not shown on this customer page, only the **assets** related to cases. 

Cheers
