### ISSUE TITLE
[BUG] Build error, pip needs upgrade

### ISSUE THREAD

**Issue by lucasjkr** [dfir-iris/iris-web#596]
**Describe the bug**
docker-compose build fails due to error installing splunk-hec

**To Reproduce**
1. Free Ubuntu install with Docker from get.docker.com
2. Follow official clone and build instructions
3. Build fails  with the following output:

_error: legacy-install-failure
54.88 
54.88 × Encountered error while trying to install package.
54.88 ╰─> splunk-hec
54.88 
54.88 note: This is an issue with the package mentioned above, not pip.
54.88 hint: See above for output from the failure.
55.18 
55.18 [notice] A new release of pip is available: 23.0.1 -> 24.2
55.18 [notice] To update, run: pip install --upgrade pip
_

**Expected behavior**
Expected the build to complete successfully

**Additional context**
I  resolved this by editing the docker/webApp/Dockerfile and docker/webApp/Dockefile.k8s and changed the final RUN command on line 33 of the compile image to:

_RUN pip install --upgrade pip && \
    pip3 install -r requirements.txt_

**Comment by whikernel** [comment]
Hello, 

Docker images shouldn't be built anymore as they are published on GCHR. Kindly see the documentation:  
https://docs.dfir-iris.org/latest/getting_started/

Best

**Comment by lucasjkr** [comment]
Good morning. I think the issue then is with the website https://dfir-iris.org

If you click View On Github, it brings you to the repo and the README correctly tell you to pull the images.

If you click the Download button, it brings you to the Quick Start, and even though the dropdown menu at top says version 2.4.12, the instructions call for cloning and checkout v2.3.7, then running docker-compose build and docker-compose up.

Specifically, the Download link brings you to
https://docs.dfir-iris.org/getting_started/

When it should bring you to either of the following:
https://docs.dfir-iris.org/2.4.12/getting_started/
https://docs.dfir-iris.org/latest/getting_started/

That was was what caused me to think I needed to build the images rather than just pull them.

That's all, thanks!
