### ISSUE TITLE
Quick start but the .env file is needed

### ISSUE THREAD

**Issue by wagga40** [dfir-iris/iris-web#6]
Hi, by default the repo doesn't have a `.env` file but a `.env.model` file. The docs basically just say that we can : 
- clone the repo
- move to the repo directory 
- execute docker-compose

But, if we do just that, the services won't start correctly because of the missing .env file.
I know this is not very hard to understand what is going on :) I can see two solutions : 
- edit the docs
- add a default `.env` file tome life easier (but less secure) for first timers.

**Comment by ecapuano** [comment]
I just built it without issue?

![image](https://user-images.githubusercontent.com/4219694/147699141-cc96cc59-ce84-46cb-a228-d9a82e2bee14.png)

**Comment by whikernel** [comment]
Hi @wagga40 

The documentation on dfir-iris.github.io will be updated to add the Copy of the env step. 
It's written on the main README but not the doc.

**Comment by wagga40** [comment]
> I just built it without issue?
> 
> ![image](https://user-images.githubusercontent.com/4219694/147699141-cc96cc59-ce84-46cb-a228-d9a82e2bee14.png)

I was referring to the docs.

**Comment by whikernel** [comment]
Closed with https://github.com/dfir-iris/iris-doc-src/commit/5a2e31dc1856f2e64475d090071115152b59f7b5 
Published website will be update soon.
