### ISSUE TITLE
[BUG] Documentation add_ioc mentions ioc_type instead of ioc_type_id

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#60]
**Describe the bug**
The API documentation at https://dfir-iris.github.io/_static/iris_api_reference_v1.0.1.html#operation/post-case-ioc-add mentions to use `ioc_type`. This returns an error. The correct field is `ioc_type_id`

The example in the documentation is correct, it's only the list of parameters (middle section of the page) that is incorrect.

**To Reproduce**
Documentation at https://dfir-iris.github.io/_static/iris_api_reference_v1.0.1.html#operation/post-case-ioc-add

**Comment by RduMarais** [comment]
Hello,
According to the template file, the correct syntax is currently `{{ ioc.type_name }}`.

**Comment by whikernel** [comment]
Hello @RduMarais, 

The IOC fields available in the report templates are actually a little differents from the API.   
For the `ioc/add` API endpoint, the IOC type ID is needed. However, in the reporting, the IOC type is resolved and available under `ioc.type_name`. 

Cheers
