### ISSUE TITLE
[FR] API v2: case status, return enum instead of integer

### ISSUE THREAD

**Issue by c8y3** [dfir-iris/iris-web#605]
POST /api/v2/cases, GET /api/v2/cases and GET /api/v2/cases/{identifier} all return the case status as a field `status_id` of type integer, whose values can range from 0 to 5. 
It would be nice to deprecate the field and replace it by a field `status` which would be an explicit enum with the following possible values: `unknown`, `false_positive`, `true_positive_with_impact`, `not_applicable`, `true_positive_without_impact`, `legitimate`.
Note: At the future time when this issue will be solved, if there are other endpoints with `status_id`, in particular the body of an update request, they should be converted too, so that the user does not have to convert from identifiers to enums.

**Comment by whikernel** [comment]
The thing is this aims to evolve to a DB-side table instead of enum, so people could actually add their own status. 
So I think we should keep the status_id field. It's the case for almost all the status, assets types, ioc types etc.

**Comment by c8y3** [comment]
This is just an idea.
When a DB table is created for case statuses, if the status name is unique and has an index, it can still be used to retrieve the status.
In theory, this would also work with case states and all other statuses. But, currently, nothing prevents the user from creating two case states with the same name.
