### ISSUE TITLE
[BUG] Default report template does not add case summary

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#61]
**Describe the bug**
When I use the default investigation report template the placeholder `{{ case.description|markdown }}` is replaced with "Empty description", although there is a case description added.

Not sure if it's related, but when I remove the MD part in the template
```
##BEGIN STYLE default##
•	##ul##
1.	##ol##
##table_header##
##table_cell##

##paragraph##
##code##
##strong##
##italic##
##END STYLE##
...
```
there is an error 

`app_1       | 2022-01-26 16:59:39 :: ERROR :: rendering_error :: __init__ :: An error occurred during rendering. Style default not defined (fsvmxdlmztkdqejiib)
`

**Comment by whikernel** [comment]
Thanks for reporting ! 

The data fed to the report generator is the same as the one in `case/export`. Could you please check that under `data` > `case` you have a valid `description` field ? 

For the second part, yes this bit is needed by the generator to be able to apply the style to the document. We'll update the documentation about that.

**Comment by cudeso** [comment]
This is in the output

`{"data": {"assets": [], "case": {"close_date": null, "description": "# Hello There\n\n## Another one", "for_customer": "zdffdemoabc", "name": "#6 - New case for TS import", "open_date": "Tue, 25 Jan 2022 00:00:00 GMT", "opened_by": "administrator", "soc_id": ""},`

**Comment by whikernel** [comment]
There's indeed an issue on the the markdown titles rendering. Some tags like `**my bold text**` are rendered correctly but not titles.  
A temporary fixe is to remove the `|markdown` from the template, in which case the markdown will not be rendered.  
In any case we'll fix that, thank for the report👍
