### ISSUE TITLE
[BUG] Dockers cannot be pulled

### ISSUE THREAD

**Issue by ClokWorx** [dfir-iris/iris-web#616]
![image](https://github.com/user-attachments/assets/cef79b00-c8a1-476a-8b08-fe14a574be41)

Fresh install of Ubuntu 22.04 and docker. Latest version of docker does not allow extends and depend_on together.

**Comment by whikernel** [comment]
Hi! 

This is due to an outdated version of docker compose. Kindly try to update the docker installation (Ubuntu doesn't ship the latest version for 22.04 afaik) 

Best

**Comment by ClokWorx** [comment]
This is the link for the compose version I downloaded https://download.docker.com/linux/ubuntu/dists/noble/pool/stable/amd64/docker-compose-plugin_2.29.7-1~ubuntu.24.04~noble_amd64.deb, this should be the latest version. Also see https://github.com/docker/compose/issues/11544#issuecomment-1964355930 where they specify this is improper usage of extends and depends_on regardless of compose version.
