### ISSUE TITLE
iriswebapp_nginx  | nginx: [emerg] cannot load certificate ...  BIO_new_file() failed (SSL: error:8000000D:system library::Permission denied:calling fopen

### ISSUE THREAD

**Issue by SysAdminSmith** [dfir-iris/iris-web#627]
Greetings:

I am attempting to spin up Iris using our AD PKI created certs.  Per the instructions, I need only place the cert.pem and key.pem in the certificates/web_certificates folder and then reference the same in .env.  I have done this:

```
user@iris:~/iris-web$ ls -lh certificates/web_certificates/
total 16K
-rw-r--r-- 1 user domain users 5.3K Oct 24 15:23 iris.dauntless.local-fullchain.pem
-rw------- 1 user domain users 1.7K Oct 24 15:23 iris.dauntless.local.key
```

and referenced them in .env:

```
user@iris:~/iris-web$ cat .env
# -- NGINX
NGINX_IMAGE_NAME=ghcr.io/dfir-iris/iriswebapp_nginx
NGINX_IMAGE_TAG=latest

SERVER_NAME=iris.dauntless.local
KEY_FILENAME=iris.dauntless.local.key
CERT_FILENAME=iris.dauntless.local-fullchain.pem
```

But continue to get:
`iriswebapp_nginx  | nginx: [emerg] cannot load certificate ...  BIO_new_file() failed (SSL: error:8000000D:system library::Permission denied:calling fopen
`
when bringing docker compose up.  

I have gone so far as to change permissions to 777 (untenable in the long run) and this did not change the permissions error. 

I am sure its a simple solution but I can't seem to stumble upon it. 

Any suggestions?

**Comment by SysAdminSmith** [comment]
Okay, this can be closed.  I commented out:

```
# Used for debugging purposes, should be deleted for production
    ports:
      - "127.0.0.1:8000:8000"
```

And this resolved the issues

**Comment by m-goess** [comment]
> Okay, this can be closed. I commented out:
> 
> ```
> # Used for debugging purposes, should be deleted for production
>     ports:
>       - "127.0.0.1:8000:8000"
> ```
> 
> And this resolved the issues

Sorry for bringing up this old topic again.
I have the same problem and have been working on it for many hours.

In which file was this line?

I also tried redeploying everything with the default env file, but I get the same error here too.

`iriswebapp_nginx     | 2026/01/14 10:17:16 [emerg] 1#1: cannot load certificate "/www/certs/iris_dev_cert.pem": BIO_new_file() failed (SSL: error:8000000D:system library::Permission denied:calling fopen(/www/certs/iris_dev_cert.pem, r) error:10080002:BIO routines::system lib)`

Even with 777 permissions, it's the same.

-------

Update i have found the solution:
I the container doesnt have permissions to the folders, so i set o+x to the folders, than it worked
