### ISSUE TITLE
[FR] Add custom fields to cases

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#64]
**Is your feature request related to a problem? Please describe.**
Currently you can only add a title, description or SOC ticket number. It would be great if there is a feature to add custom fields. These custom fields can for example be used for filtering or statistics (fe. 'type of case/investigation').

**Describe the solution you'd like**
- Add one or more custom fields
- - fieldname
- - fieldtype (string, integer, list)
- - - list comes from a predefined list (can for example be added when user defines/add the custom field); lists are represented in a dropdown list
-- mandatory yes/no

**Comment by whikernel** [comment]
FYI : we'll extend this custom attributes to all case objects
