### ISSUE TITLE
[BUG] Change default credentials results in app not starting

### ISSUE THREAD

**Issue by darrinh** [dfir-iris/iris-web#641]
**Describe the bug**
The docs says copy .env.model to .env and run docker to test. To use in production
the docs says to update the following credentials:

POSTGRES_PASSWORD
POSTGRES_ADMIN_PASSWORD
IRIS_SECRET_KEY
IRIS_SECURITY_PASSWORD_SALT

**To Reproduce**
1. copy .env.model to .env
2. change credentials as listed above
3. remove previous test containers/images
4. run docker compose up

** results **

```
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_worker    | IRISwebapp is unavailable - sleeping
iriswebapp_nginx     | 2024/11/25 04:12:19 [error] 16#16: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: iris.app.dev, request: "GET / HTTP/1.1", upstream: "http://172.19.0.2:8000/", host: "127.0.0.1"
iriswebapp_nginx     | 127.0.0.1 - - [25/Nov/2024:04:12:19 +0000] "GET / HTTP/1.1" 502 497 "-" "curl/7.88.1" "-"
iriswebapp_nginx     | 2024/11/25 04:12:19 [info] 16#16: *13 client 127.0.0.1 closed keepalive connection

```

 - OS: ubuntu 22.04

Is there somewhere the creds are supposed to be changed or am I missing a step somewhere?

thanks

**Comment by darrinh** [comment]
ok, figured it out.

**Comment by ReDoneX0** [comment]
@darrinh what was the cause? I am running into the same issue
