### ISSUE TITLE
[FR] Have unique UUID for case ID

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#66]
**Is your feature request related to a problem? Please describe.**
Instead of only having an ID ("case id"), use a UUID. This makes cases transportable across multiple instances of IRIS. This should not replace the ID displayed in the UI, but underneath (ie. export, API), the UUID can be used as reference.

**Comment by adulau** [comment]
I would strongly support the idea. This could be also used to shared cases via other sharing mechanisms such as MISP.
