### ISSUE TITLE
[FR] Upload screenshots to notes

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#68]
**Is your feature request related to a problem? Please describe.**
Screenshots are often used as a form of evidence. It would be great if you can add screenshots to notes. Currently you have to reference another (external) file in the MD. Ideal solution allows to upload an image/screenshot to a note and then have it displayed within the note.

**Describe the solution you'd like**
- Upload screenshot in note
- - From file on disk
- - Or from clipboard (similar to Github issues)
- Include screenshot in the notes in a generated report

**Comment by whikernel** [comment]
Thanks @cudeso ! This joins #30. 
We'll close this one and keep the other.
