### ISSUE TITLE
Loss free update of the database container

### ISSUE THREAD

**Issue by m-terlinde** [dfir-iris/iris-web#78]
Hey guys,

I was just wondering, what happens to the database during an container update. As far as I can see, it is not planned to ever update the database container in a pain free manner?
So if I want to update the database container (because of security fixes or so), I should make a pg_dump and then import it back?

Wouldn't it be a bit _nicer_ to create an own volume for the database?

I think the database scheme migrations between IRIS updates are handled in the web app, right? So this shouldn't create any issues?

Not sure, if this is a feature request by the meaning or just me overseeing something obvious. Not sure as well, if this would qualify as FR, so I didn't use the template.

Cheers,
Matthias

**Comment by whikernel** [comment]
Hi @m-terlinde,

Unless I'm mistaken, the Postges docker we are using mounts by default the ``/var/lib/postgresql/data`` to a volume on the host. You can verify that by doing a ``docker inspect <iris_db_instance>``. 

Here is mine : 

![image](https://user-images.githubusercontent.com/74464599/156518890-3ab571f7-8f3f-4a9e-bf40-86ce635e6ba2.png)

When you rebuild the Postgres docker instance, let's say for security fixes, it should reuse the docker same volume. 
You can test it - not in prod :D - with : 
- ``docker-compose stop db``
- ``docker-compose build db``
- ``docker-compose up db``
 
The data should be back. A ``docker-compose down``or ``docker-compose down --db`` would however also destroy the volume. 

For the migrations of DB schema, they are indeed handled by the webapp docker itself  👍  

Please let us know if it works for you and if that answers your concern. 
Cheers !

**Comment by wagga40** [comment]
> We could however put a named volume for more resiliency - is that what you are suggesting ?

I really think this is a better idea for newcomers. Because in the current case we are a command away of loosing data.

**Comment by m-terlinde** [comment]
> We could put a named volume for more resiliency - is that what you are suggesting ?

Yes, that's exaclty, what I was suggesting. At least for me it was not clear, that down destroys the saved data.
