### ISSUE TITLE
[BUG] "Switch case" button stays grey

### ISSUE THREAD

**Issue by m-terlinde** [dfir-iris/iris-web#81]
**Describe the bug**
When you abort the "Switch context" screen, the icon stays grey.

**To Reproduce**
1. Click on the "Switch case" button
2. In the pop-up, click "close"
3. See error

**Expected behavior**
The icon should not stay grey ;).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10097313/156946814-40559d67-c9b0-4e1d-9632-57909870ba29.png)

**Desktop**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 97.0.2

**Additional context**
Not related to the bug itself but it is very confusing to have the "abort" operation on the right side. Also it's style is more visual cognizable than the "save" operation. I think it should be the other way around.

Oh and the template misses double-points at "Browser" and "Version" in the `Desktop` and `Smartphone` section.

**Comment by whikernel** [comment]
Fixed in [v1.4.0 ](https://github.com/dfir-iris/iris-web/releases/tag/v1.4.0)
